CHANGELOG.md, package.json
- 修复：`<Input />` 组件 `textarea` 调整大小时的 UI 展示问题 [#152](https://github.com/XiaoMi/hiui/issues/152)
- 修复：`<Select />` 组件单选、多选高度不一致的问题 [#201](https://github.com/XiaoMi/hiui/issues/201)
- 修复：`<Select />` 组件多选禁用还可以勾选的问题 [#218](https://github.com/XiaoMi/hiui/issues/218)
- 修复：`<Cascader />` 组件 `displayRender` 会触发两次的问题 [#246](https://github.com/XiaoMi/hiui/issues/246)
- 修复： `<Radio />` 组件在 `id === 0` 时回调参数错误的问题 [#259](https://github.com/XiaoMi/hiui/issues/259)
- 修复 ：`<Input />` 组件前、后缀的内容被带回到实际值的问题 [#282](https://github.com/XiaoMi/hiui/issues/282)
=> update version and changelog

libs/doc-viewer/components/EditorWrapper.jsx
增加 LiveEditor 的禁用状态控制：展开时可用，收起时禁用。这样做是为了防止在组件测试时不停按 <kbd>Tab</kbd> 键会聚焦到代码框里的显示错误。
=> feat: add editor disable control

CHANGELOG.md, docs/zh-CN/components/theme.mdx, package.json
- 新增 `<Breadcrumb />` 面包屑组件 [#573](https://github.com/XiaoMi/hiui/issues/573)
- 新增 `<Tree />` 线型展示模式 [#549](https://github.com/XiaoMi/hiui/issues/549)
- 修复 `<Upload />` 中的自定义上传同一个文件失败的问题 [#567](https://github.com/XiaoMi/hiui/issues/567)
- 修复 `<Switch />` 重复渲染问题 [#565](https://github.com/XiaoMi/hiui/issues/565)
- 修复 `<Collapse />` activeId 无效的问题 [#560](https://github.com/XiaoMi/hiui/issues/560)
=> chore: update version and changelog

components/tree/tree-legacy/util.js, components/tree/util.js
=> fix(tree): 修复清除搜索条件无法收缩问题

CHANGELOG.md, components/table/HeaderTable.jsx, components/table/Row.jsx, components/table/Table.jsx
=> fix: #1752

CHANGELOG.md, components/table/Cell.jsx
=> fix: #1759

components/tabs/style/index.scss
=> fix: 修复tabs组件flex被压缩过小导致不可点击

.gitignore, packages/ui/space/src/styles/space.scss, packages/ui/space/stories/auto-size.stories.tsx
1.设置item宽度为100%；
2.修改示例“自定义间距大小”，去掉 Counter 组件的 autoFocus 防止每次打开页面时会锚点到该位置；
3.git忽略文件中增加了2项规则：.history/ dist-github/**
=> fix(space):修复item宽度问题

packages/ui/back-top/src/BackTop.tsx, packages/ui/back-top/src/styles/back-top.scss, packages/ui/back-top/stories/basic.stories.tsx, packages/ui/back-top/stories/compose.stories.tsx, packages/ui/back-top/stories/custom.stories.tsx, packages/ui/back-top/stories/settings.stories.tsx
1.svg 类样式被覆盖，改为行内样式
2.stories 代码精简
=> fix(back-top): 修复 svg 样式被覆盖

packages/ui/table/src/TableBody.tsx
closed #2220 
列较多超出容器时，空状态内容显示在容器外，要让空状态内容一直显示在可见容器的中间，需要做2点改造：
1.在空状态内容外面包一层 div，动态设置该 div 宽度和可见容器宽度一致
2.给该 div 设置为 sticky 布局，且 left 值为0
=> fix(table): 修复列较多超出容器时空状态显示异常

packages/ui/date-picker/src/utils/index.tsx
closed #2217 
1.更新 PRCLunar.json CDN数据
2.更新代码中请求链接查询参数，以获取到最新数据
=> fix(date-picker): 修复预置农历错误

packages/ui/check-select/src/use-check-select.ts
=> fix(CheckSelect): 修复异步加载数据选中项未缓存问题

packages/ui/modal/src/Modal.tsx
closed #2241 
1.由于弹窗打开动画使用了缩放，导致内容中有动态计算宽高的场景下，计算出的值不是正常的元素大小
2.增加了 onEntered API 在打开动画结束时，用户自行在该回调函数中处理（例如：刷新一遍组件）
=> feat(modal): 增加打开动画结束时的回调函数参数

packages/ui/table/src/hooks/use-async-switch.ts, packages/ui/table/src/styles/table.scss, packages/ui/table/src/use-table.ts, packages/ui/table/stories/on-load-children.stories.tsx
closed #2263 
修改点：
1.增加子节点的算法，基于动态的fieldKey参数的值来判断
2.顺带修改了一个样式问题：如果全局设置了box-sizing: border-box，会导致resizable模式下的操作条不展示
=> fix(table): 修复onLoadChildren bug

packages/ui/form/src/use-form-field.ts, packages/ui/form/stories/basic.stories.tsx
closed #2268 
问题原因：
在输入框中，fieldValidate 方法中接收的 value 的类型总是 string，导致字段校验设置为 number 类型总是不通过
修改点：
1.判断 fieldValidate 方法中接收的 value 如果是字符串数字则将其转换为数字类型
=> fix(form): 处理校验器接收的字符串数字类型（#2268）

packages/ui/time-picker/src/TimePicker.tsx
closed #2277 
问题原因：
处理初始值，固定是按照 HH:mm:ss 格式去处理，没有按照用户传入的 format 来处理，所以如果传入时间戳时，返回的是时分秒的格式。
解决方案：
给处理初始值的函数中传入用户传入的 format，按照 format 来格式化，默认是按照 HH:mm:ss 格式处理
=> fix(time-picker): 修复初始值显示格式问题

packages/ui/notification/src/styles/notification.scss
closed #2273 
问题原因：
之前设置的icon大小是设置的svg的font-size，当svg的样式有别的模块给覆盖时，导致icon大小设置不生效
解决方案：
不在svg上面设置font-size，设置它的父节点的font-size
=> fix(notification): 修改icon样式

.changeset/fifty-moons-yell.md, packages/ui/locale-context/package.json, packages/ui/locale-context/src/LocaleContext.tsx
只有当获取的值为 null 或 undefined 时，控制台才打印提示。
=> fix(locale-context): 优化获取文案时的空值判断

packages/ui/table/src/TableBody.tsx, packages/ui/table/src/hooks/use-col-width.ts, packages/ui/table/src/use-table.ts
1.修改元素宽度自适应bug
-测量元素在切换空/结果列时元素会变化，需要重新绑定对元素resize的监测
2.修改虚拟列表宽度计算逻辑。
-虚拟列表在字段变化时，还是需要通过容器宽度来计算表头宽度
=> fix: measure row bindlogic and virtual width logic

.changeset/large-moons-care.md, .changeset/nice-parrots-run.md, packages/ui/drawer/package.json, yarn.lock
closed #2485 
问题原因：依赖的 react-transition-group 版本问题，4.4.5 版本中没有入场动画，4.4.2 版本是正常的
解决方案：将组件中 react-transition-group 的依赖版本固定为 4.4.2
=> fix(drawer): #2485

.changeset/seven-hairs-greet.md, packages/icons/package.json
closed #2502 
package.json 增加配置： sideEffects: ["*.scss", "*.scss.js", "./lib/*/index.js"]
其中 "*.scss" 是给组件 rollup 打包时标识为副作用的文件，"*.scss.js", "./lib/*/index.js" 是给使用组件打包时标识为副作用的文件
=> perf(icons): #2502

.changeset/plenty-tools-prove.md, .changeset/quick-socks-relax.md, packages/ui/table/src/TableBody.tsx, packages/ui/table/src/TableEmbedRow.tsx, packages/ui/table/src/hooks/use-col-width.ts, packages/ui/table/src/hooks/use-expand.ts, packages/ui/table/src/use-table.ts, packages/utils/tree-utils/src/index.ts
=> perf(table): 表格性能优化

.changeset/chilled-wolves-love.md, .changeset/fast-ants-bake.md, packages/ui/notification/src/Notification.tsx, packages/ui/notification/src/styles/notification.scss, packages/ui/notification/stories/index.stories.tsx, packages/ui/notification/stories/size.stories.tsx
=> feat(notification): add size api

.changeset/nasty-students-drive.md, .changeset/tender-yaks-appear.md, packages/ui/list/src/ListItem.tsx, packages/ui/list/src/types.ts, packages/ui/list/stories/avatar.stories.tsx, packages/ui/list/stories/index.stories.tsx
=> feat(list): #2574

.changeset/mean-ants-shave.md, .changeset/odd-tomatoes-grow.md, packages/ui/alert/src/Alert.tsx, packages/ui/alert/src/styles/alert.scss, packages/ui/alert/stories/index.stories.tsx, packages/ui/alert/stories/size.stories.tsx
=> feat(alert): add size api

.changeset/heavy-tools-itch.md, .changeset/unlucky-scissors-tease.md, packages/ui/dropdown/src/Dropdown.tsx, packages/ui/dropdown/src/styles/dropdown.scss, packages/ui/dropdown/stories/icon.stories.tsx, packages/ui/dropdown/stories/index.stories.tsx, packages/ui/dropdown/stories/size.stories.tsx
=> feat(dropdown): add size api

.changeset/green-teachers-travel.md, .changeset/sixty-fishes-tan.md, packages/ui/tree/src/Tree.tsx, packages/ui/tree/src/types.ts, packages/ui/tree/stories/index.stories.tsx, packages/ui/tree/stories/scroll-to.stories.tsx
组件 ref 支持 scrollTo 方法（代理调用 rc-virtual-list 的 scrollTo 方法）
=> feat(tree): 增加 scrollTo 方法

.changeset/chatty-singers-sin.md, .changeset/eight-jars-roll.md, packages/ui/textarea/src/styles/textarea.scss, packages/ui/textarea/stories/disabled.stories.tsx, packages/ui/textarea/stories/index.stories.tsx
=> fix(textarea): 禁用状态背景色改为G10 (#2637)

.github/workflows/release.yml, .github/workflows/version.yml
由于升级到rollup3，需要的node版本号要大于14.21.x，所以同步修改CI中的node版本
=> ci: 更新CI中的node版本号

.changeset/eighty-moons-rest.md, .changeset/slow-tables-guess.md, packages/ui/tag/src/Tag.tsx, packages/ui/tag/stories/max-width.stories.tsx
closed #2678 
增加 tooltipProps 参数，用户可以自己控制是否需要禁用 Tooltip 的 portal
=> feat(tag): 增加tooltipProps参数 (#2678)

.changeset/hip-falcons-cry.md, .changeset/olive-goats-wink.md, packages/ui/select/src/Select.tsx, packages/ui/select/stories/custom-render.stories.tsx, packages/ui/select/stories/index.stories.tsx
=> feat(select): add customRender api (#2765)

.changeset/curly-pans-matter.md, .changeset/lucky-plums-greet.md, packages/ui/table/src/hooks/use-check.ts
=> fix(table): 修复全选时 onChange 第 4 个参数返回 undefined 问题 (#2789)

.changeset/late-birds-jam.md, .changeset/orange-seals-laugh.md, packages/ui/descriptions/src/Cell.tsx, packages/ui/descriptions/src/Descriptions.tsx, packages/ui/descriptions/src/Row.tsx, packages/ui/descriptions/src/styles/descriptions.scss
closed #2796 
columnGap属性支持自定义列间距，注：应用于无边框场景下
=> feat(descriptions): 新增支持自定义列间距功能(#2796)

.changeset/nervous-scissors-care.md, .changeset/purple-laws-check.md, packages/ui/table/src/hooks/use-check.ts
=> fix(table): 修复同时设置 fieldKey 和 rowSelection 时 onChange 回调参数异常问题 (#2836)

.changeset/olive-trains-joke.md, .changeset/tidy-rings-burn.md, packages/ui/date-picker/src/utils/index.tsx
修改设置日期顺序至修改月份后，防止日期被设置到不存在该日期的月份
closed #2853
=> fix(date-picker): 修复datepicker显示农历时2月中1月农历显示错误问题 (#2853)

.github/workflows/release.yml
=> feat: 支持自动化发布Releases日志

.changeset/cold-bobcats-knock.md, .changeset/itchy-suns-sleep.md, packages/ui/form/stories/label-placement.stories.tsx, packages/ui/table/src/use-table.ts, packages/ui/table/stories/draggable.stories.tsx
=> fix(table): 修复 onDragStart 事件不触发问题 (#2858)

.changeset/khaki-panthers-clean.md, .changeset/rude-baboons-explode.md, .changeset/tame-sloths-begin.md, packages/ui/table/src/TableBody.tsx
=> fix(table): 修复虚拟列表maxHeight无法支持字符串问题(#2846)

.changeset/five-ads-drum.md, .changeset/twenty-ligers-flash.md, packages/ui/modal/src/Modal.tsx, packages/ui/modal/src/use-modal.ts
=> feat(modal): 新增自定义zIndex功能

.changeset/nasty-oranges-brush.md, .changeset/tiny-bananas-wonder.md, packages/ui/descriptions/src/Descriptions.tsx, packages/ui/descriptions/src/util.ts
=> feat(descriptions): 支持配置字段别名(#2873)

.changeset/four-pets-sparkle.md, .changeset/soft-spies-march.md, packages/ui/breadcrumb/src/Breadcrumb.tsx, packages/ui/breadcrumb/src/util.ts
=> feat(breadcrumb): 支持配置字段别名(#2885)

.changeset/fuzzy-buttons-worry.md, .changeset/wise-walls-arrive.md, packages/ui/dropdown/src/Dropdown.tsx, packages/ui/dropdown/src/utils/index.ts
=> feat(dropdown): 支持配置字段别名(#2883)

.changeset/dull-carrots-shout.md, .changeset/soft-actors-perform.md, packages/ui/number-input/src/NumberInput.tsx, packages/ui/number-input/src/styles/number-input.scss, packages/ui/number-input/stories/addon.stories.tsx, packages/ui/number-input/stories/index.stories.tsx
=> feat(number-input): 新增前缀后缀内容扩展(#2906)

.changeset/cyan-rules-sparkle.md, .changeset/funny-zebras-pretend.md, packages/ui/date-picker/src/DatePicker.tsx, packages/ui/date-picker/src/components/root.tsx, packages/ui/date-picker/src/styles/date-picker.scss, packages/ui/date-picker/src/types.ts, packages/ui/date-picker/stories/addon.stories.tsx, packages/ui/date-picker/stories/index.stories.tsx
=> feat(date-picker): 新增前缀后缀内容扩展(#2894)

.changeset/rude-sheep-argue.md, .changeset/silent-gifts-suffer.md, packages/ui/time-picker/src/TimePicker.tsx, packages/ui/time-picker/src/styles/time-picker.scss, packages/ui/time-picker/stories/addon.stories.tsx, packages/ui/time-picker/stories/index.stories.tsx
=> feat(time-picker): 新增前缀后缀内容扩展(#2903)

.changeset/orange-dolphins-arrive.md, .changeset/plenty-dodos-fold.md, packages/ui/tree-select/src/TreeSelect.tsx, packages/ui/tree-select/stories/custom-render.stories.tsx, packages/ui/tree-select/stories/index.stories.tsx
=> feat(tree-select): 新增自定义触发器(#2884)

.changeset/calm-coins-leave.md, .changeset/orange-waves-allow.md, packages/ui/upload/src/NormalUpload.tsx, packages/ui/upload/src/PictureListUpload.tsx, packages/ui/upload/src/PictureUpload.tsx, packages/ui/upload/src/hooks/use-upload.ts, packages/ui/upload/src/styles/upload.scss
=> fix(upload): #2928

packages/ui/table/src/hooks/use-col-width.ts
=> fix(table): 修复列更新问题 (#2923)

.changeset/chilly-squids-talk.md, .changeset/lemon-fireants-glow.md, packages/ui/tree/src/TreeNode.tsx
=> fix(tree): 修复Firefox中组件拖拽报错问题(#2941)

.changeset/five-mails-beg.md, .changeset/plenty-mice-thank.md, .changeset/red-gorillas-count.md, .changeset/selfish-steaks-think.md, packages/ui/input/src/MockInput.tsx, packages/ui/select/src/Select.tsx
=> feat(input): MockInput 没有匹配到值时默认展示 value 值

.changeset/dull-birds-hang.md, .changeset/odd-ladybugs-boil.md, packages/ui/tree/src/hooks/use-edit.ts, packages/ui/tree/src/use-tree-action.tsx, packages/ui/tree/src/utils/tree.ts
=> fix(tree): 修复组件指定 fieldNames={{ title: 'name' }} 后，menuOptions 里 type 为 editNode 时会出现改不了节点的情况

.changeset/four-cameras-float.md, .changeset/healthy-suits-drop.md, packages/ui/check-tree-select/src/CheckTreeSelect.tsx, packages/ui/check-tree-select/stories/index.stories.tsx, packages/ui/check-tree-select/stories/only-checked.stories.tsx
=> feat(check-tree-select): 新增支持过滤已选择项(#2951)

.changeset/silver-ads-jog.md, .changeset/slow-bottles-talk.md, packages/ui/date-picker/src/DatePicker.tsx, packages/ui/date-picker/src/components/date-range-time-panel.tsx, packages/ui/date-picker/src/components/footer.tsx, packages/ui/date-picker/src/components/panel.tsx, packages/ui/date-picker/src/components/range-panel.tsx, packages/ui/date-picker/src/styles/date-picker.scss, packages/ui/date-picker/src/types.ts, packages/ui/date-picker/stories/index.stories.tsx, packages/ui/date-picker/stories/need-confirm.stories.tsx
closed #2979 
增加 needConfirm 和 onConfirm api
=> feat(date-picker): Add needConfirm and onConfirm api (#2979)

.changeset/breezy-berries-marry.md, .changeset/grumpy-tips-peel.md, .changeset/lovely-suns-breathe.md, .changeset/silver-bulldogs-provide.md, packages/ui/check-cascader/src/CheckCascader.tsx, packages/ui/check-cascader/src/CheckCascaderMenuList.tsx, packages/ui/check-cascader/src/utils/index.ts
=> fix(check-cascader): 修复checkedMode="PARENT"模式下搜索后子节点无法勾选的问题

.changeset/perfect-swans-draw.md, .changeset/selfish-apricots-applaud.md, .changeset/yellow-chicken-shout.md, packages/ui/cascader/src/Cascader.tsx, packages/ui/check-cascader/src/CheckCascader.tsx, packages/ui/check-tree-select/src/CheckTreeSelect.tsx, packages/ui/check-tree-select/stories/searchable.stories.tsx, packages/ui/tree-select/src/TreeSelect.tsx
=> fix: 修复TreeSelect、CheckTreeSelect、Cascader、CheckCascader设置Keyword后数据没有过滤的问题

.changeset/sixty-rings-scream.md, .changeset/tame-rats-wait.md, packages/ui/check-cascader/src/CheckCascader.tsx
=> perf(check-cascader): 优化大数据下勾选根节点时卡顿 (#2998)

.changeset/cyan-ads-sparkle.md, .changeset/grumpy-swans-sing.md, .changeset/plenty-jeans-guess.md, .changeset/sharp-days-repeat.md, packages/ui/table/src/BaseTable.tsx, packages/ui/table/src/TableBody.tsx, packages/ui/table/src/TheadContent.tsx, packages/ui/table/src/context.ts, packages/ui/table/src/hooks/use-col-width.ts, packages/ui/table/src/use-table.ts, packages/ui/table/stories/resizable.stories.tsx, packages/ui/table/stories/virtual.stories.tsx, patches/rc-virtual-list+3.4.8.patch
=> feat(table): Add onResizeStop and onVisibleChange api

.changeset/fifty-snakes-invent.md, packages/ui/drawer/src/Drawer.tsx
=> fix(drawer): 修复 width 和 height 类型不支持字符串问题 (#3013)

.changeset/fresh-scissors-complain.md, packages/ui/input/src/types.ts, packages/ui/input/src/utils/index.ts
=> fix(input): 修复 type="X" 时最后一位无法输入 X 的问题 (#3023)

README.EN.md, README.md
* Referenced the file README.EN.md
* Create README.EN.md
=> README.EN.md file created, English README file provided.

.changeset/clever-monkeys-speak.md, .changeset/rude-ways-look.md, packages/hooks/use-search-mode/src/index.ts, packages/ui/check-select/src/CheckSelect.tsx, packages/ui/check-select/stories/data-source.stories.tsx, packages/ui/select/src/Select.tsx, packages/ui/select/stories/data-source.stories.tsx
=> feat(select&check-select): Add searchOnInit api (#3004)

.changeset/rare-needles-hang.md, packages/ui/dropdown/src/Dropdown.tsx
=> fix(dropdown): 修复父节点设置disabled后依然可以点击的问题 (#3030)

.changeset/good-comics-smell.md, package.json, packages/ui/scrollbar/package.json, yarn.lock
Scrollbar 组件中去掉 perfect-scrollbar 依赖,因为通过 patch-package 修改了这个库的源码,所以必现将依赖去掉,这样才能将修改的源码打包到 Scrollbar 组件的 lib 中
=> fix(scrollbar): 去掉 perfect-scrollbar 依赖

.changeset/moody-bikes-raise.md, packages/ui/table/src/TableBody.tsx, packages/ui/table/src/types.ts, packages/ui/table/src/use-table.ts, packages/ui/table/stories/virtual.stories.tsx
feat(table): 虚拟列表下，支持设置滚动位置 (#3044)
=> feat(table): 虚拟列表下，支持设置滚动位置 (#3044)

.changeset/quick-teachers-glow.md, packages/ui/form/src/FormItem.tsx, packages/ui/form/src/use-form.ts
closed #3120 
同步修改：更新 FormItemProps 的 children 类型以支持渲染函数
=> fix(form): 修复特殊场景下 validate() 执行后获取不到最新值问题 (#3120)

.changeset/many-frogs-fail.md, packages/ui/form/src/Form.tsx, packages/ui/form/src/styles/form.scss
1. 错误提示字号改为 12px
2. 必填星号调整为显示在右侧
3. 标题和控件间距改为 6px
4. 包裹控件容器设置最小高度 32px
5. 默认不显示标题冒号
=> feat(form): 新版 Form (5.0)

.changeset/neat-paws-call.md, packages/ui/tag-input/src/TagInputMock.tsx
=> fix(tag-input): 修复 TagInputMock 组件中标签最大数量逻辑及更新 tagsWidth 的处理方式 (#3260)

packages/ui/table/src/types.ts
TableColumnItem类型支持了泛型，让render等方法的item可以直接推导出类型
=> feat(table): tablecolumnitem 支持泛型
