XiaoMi/hiui

components/table/body.js
=> 修改import时的bug

components/table/body.js, components/table/index.js, package.json
```js
const rowSelection = {
selectedRowKeys,
onChange: (selectedRowKeys, rows) => {
this.setState({selectedRowKeys})
},
getCheckboxProps: record => ({
disabled: parseInt(record.age) % 2 === 0, // Column configuration not to be checked
name: record.name
})
}
```
1.  you need to pass selectedRowKeys to rowselection
2.  when table rowselection onChange event trigger, you need to setState "selectedRowKeys"
=> 修改table多选的bug

components/table/clickOuterside.js, components/table/index.js, components/table/style/Table.scss, docs/en-US/table.md, docs/zh-CN/table.md
1. 右上角设置checkbox
2. 增加striped 样式
=> # table bug fix memory

components/table/index.js, docs/en-US/table.md
=> # table hotfix

components/table/index.js
1. remove table console
2. fix tabe page bug
=> # table page

components/table/body.js, components/table/header.js, components/table/index.js, docs/zh-CN/table.md
=> # table scroll

components/table/checkbox/index.js, components/tree/Tree.js, components/tree/TreeNode.js, components/tree/util.js, docs/zh-CN/tree.md
1. add default
2. add semi checked
3. add disabled
4. add tree node click
=> # feature/tree

components/button/Button.js, components/table/index.js
fix table sort bug and button click bug
=> fix table sort bug

components/button/Button.js, docs/zh-CN/components/button.md
=> # button文本和按钮不兼容的bug

site/index.html, site/index.template.html, site/view/Home/index.js
=> docs: add hotjar

components/counter/index.js, components/counter/style/index.scss, components/input/index.js, components/input/style/index.scss
- 修复 Input 组件没有输入时清空按钮的展示问题
- 修复  Input 组件 suffix/prefix 下 Input 组件存在的没有对齐问题
- 修复 Counter 组件的展示 onBlur 后的展示 bug
- 修复 Counter 组件的 +/- 未对齐问题
=> 修复 Counter 组件和 Input 组件 bug

components/loading/index.js, components/loading/style/index.scss, docs/en-US/components/loading.md, docs/zh-CN/components/loading.md, site/view/Home/style/index.scss
重写 loading 组件，api 保持不变
新的 loading 组件样式
=> feat(loading): new loading style

components/popper/index.js, components/tooltip/index.js, docs/en-US/components/tooltip.md, docs/zh-CN/components/tooltip.md
- Dropdown
- SubMenu
- Popover
- Select
- Tabs
=> feat(tooltip): add open api

docs/en-US/components/tabs.md
=> fix: Tabs en doc  #221

CHANGELOG.md, package.json
- 新增：`<Timeline />` 时间轴组件 [#239](https://github.com/XiaoMi/hiui/issues/239)
- 新增：`<Loading />` 组件 UI 样式 [#238](https://github.com/XiaoMi/hiui/issues/238)
- 新增：`<Tooltip />` 组件 api 调用功能 [#240](https://github.com/XiaoMi/hiui/issues/240)
=> update rc version and changelog

components/form/item.js, components/form/style/index.scss, docs/en-US/components/form.md, docs/zh-CN/components/form.md
更新 Form 组件样式和文档 #245 #244 
#253 待修复
=> fix #245 #244

components/select/SelectDropdown.js, components/select/style/select-input.scss
=> fix #201 #218

components/loading/style/index.scss, components/tabs/style/index.scss
=> fix(Tabs): trembling when switch

components/rate/Rate.js, docs/en-US/components/rate.md, docs/zh-CN/components/rate.md
=> fix(Rate): defaultValue bug

components/menu/index.js
=> fix:menu mini toggle 子菜单不关闭bug

components/button/Button.js
=> fix(Button): resolve localeDatas warning

components/popover/index.js
=> fix :ref error

CHANGELOG.md, package.json
- 修复：`<Select />` 组件搜索特殊字符造成的崩溃问题 [#294](https://github.com/XiaoMi/hiui/issues/294)
=> update version and changelog

CHANGELOG.md, components/form/index.js, components/form/item.js, components/form/style/index.scss, docs/en-US/components/form.md, docs/zh-CN/components/form.md
`form-item` 修改为 flex 布局
🚗🚗🚗🚗🚗🚗🚗🚗🚗🚗🚗🚗🚗
未写 `trigger` 时不触发 `onChange, onBlur` 验证
=> fix(form): #295 #296

components/button/Button.js, components/button/style/index.scss, docs/demo/button/section-link.jsx, docs/demo/button/section-loading.jsx, docs/demo/button/section-standard.jsx, docs/zh-CN/components/button.mdx
=> fix(button): 2.0 loading button

components/button/Button.js, components/button/style/index.scss, docs/demo/button/section-link.jsx, docs/demo/button/section-loading.jsx, docs/demo/button/section-standard.jsx, docs/demo/stepper/section-vertical.jsx, docs/zh-CN/components/button.mdx, site/view/Component/index.js, site/view/index.js, site/view/routes.js
=> fix(button): loading button

components/loading/index.js, components/style/icon/index.scss, components/tree/TreeItem.js, components/tree/TreeNode.js, components/tree/style/index.scss, package.json
=> fix loading

components/select/Select.js, components/select/SelectDropdown.js, components/select/SelectInput.js, components/select/style/select-dropdown.scss, components/tabs/Tabs.js, components/tabs/tabs-legacy/Tabs.js, docs/demo/select/section-async-multiple.jsx, docs/demo/select/section-async.jsx, docs/demo/select/section-ban.jsx, docs/demo/select/section-custom.jsx, docs/demo/select/section-multiple.jsx, docs/demo/select/section-single-multiple.jsx, docs/demo/select/section-type.jsx, docs/zh-CN/components/select.mdx, site/view/Component/Header/index.js
=> feat: update select

components/date-picker/Calender.js, components/date-picker/DatePanel.js, components/date-picker/DateRangePanel.js, components/date-picker/Time.js, components/date-picker/TimePanel.js, components/date-picker/TimePeriodPanel.js, components/date-picker/TimePicker.js, components/date-picker/TimeRangePanel.js, components/date-picker/WeekRangePanel.js, components/date-picker/style/index.scss, components/locales/en-US.js, components/locales/zh-CN.js
=> fix:Datepicker i18n

components/upload/Upload.js, components/upload/UploadDrag.js, components/upload/UploadPhoto.js, components/upload/UploadPictureCard.js, components/upload/style/index.scss
1、Upload 样式调整
2、Upload maxCount 的失效问题
=> Upload Style

site/style/index.scss, site/view/index.js
=> add version tag

components/button/style/index.scss
=> fix(button): remove position relative

build/webpack.config.dev.js, components/form/Form.js, components/form/Item.js, components/form/index.js, components/input/Input.js, components/input/util.js, components/locales/en-US.js, components/locales/zh-CN.js, docs/demo/input/section-other.jsx, docs/demo/input/section-position.jsx, docs/demo/input/section-state.jsx, docs/demo/input/section-type.jsx, docs/zh-CN/components/form.mdx, docs/zh-CN/components/input.mdx
- Input
- 添加 clearable 属性
- 合并 prefix, prepend    suffix, append
- 修复手机号、银行卡、身份证格式化功能
- 废弃 required 属性
=> Feature/develop form&input

components/form/index.js, components/form/item.js, components/locales/en-US.js, components/locales/zh-CN.js
=> feat(form): add showColon prop

components/context/index.js, docs/demo/form/section-check.jsx
=> fix: wrapped component ref

components/button/Button.js, components/button/style/index.scss, docs/demo/button/section-link.jsx, docs/demo/icon/section-nest.jsx, docs/zh-CN/components/icon.mdx
fix #492 
修正 Button 内嵌只有一个 Icon 时的间距问题；
重构 Button 样式，为每种形态增加 :focus 样式。
=> 修正 Button 内嵌只有一个 Icon 时的间距问题

components/select/style/select-dropdown.scss
=> fix select multiple bug

docs/demo/button/section-loading.jsx, docs/demo/dropdown/section-extend.jsx, docs/demo/dropdown/section-trigger.jsx, docs/demo/input/section-other.jsx, docs/demo/input/section-position.jsx, docs/zh-CN/components/select.mdx
=> docs: check input demo & fix #482

components/_util/SwitchVersion.js, components/date-picker/BasePicker.js, components/date-picker/DatePicker.js, components/date-picker/datepicker-legacy/DatePicker.js, components/date-picker/index.js, package-lock.json
fix: [540](https://github.com/XiaoMi/hiui/issues/540)
=> fix: 展开位置错误;fix: format 函数丢失

components/counter/Counter.js, components/table/index.js, docs/demo/counter/section-base.jsx
1. 点击- 不能减少到0以下
2. 没有设置min max会显示NaN
#625 #593 #247
=> ## 修复 counter bug 和 table bug

components/_util/SwitchVersion.js, components/context/index.js
=> fix: duplicate provider

components/form/Item.js
=> feat：label support ReactNode

CHANGELOG.md, docs/zh-CN/components/changelog.mdx, package.json
- 修复 `<Checkbox />` 同时渲染多个 context provider 的问题 [#649](https://github.com/XiaoMi/hiui/issues/649)
- 修复 `<Select />` 同等宽度下，多选和单选的 placeholder 和展开箭头没有对齐的问题 [#661](https://github.com/XiaoMi/hiui/issues/661)
- 修复 `<Table />` 表头渲染不正确的问题 [#625](https://github.com/XiaoMi/hiui/issues/625)
- 修复 `<Popover />` 初次 hover 触发时移入气泡框，气泡框会消失的问题 [#650](https://github.com/XiaoMi/hiui/issues/650)
- 修复 `<Counter />` 部分情况下展示不正确的问题 [#593](https://github.com/XiaoMi/hiui/issues/593)
- 修复 `<Pagination />` 关于 "javascript:void(0)" 的警告 [#656](https://github.com/XiaoMi/hiui/issues/656)
- 修复 `<TimePicker />` 层级太低的问题 [#637](https://github.com/XiaoMi/hiui/issues/637)
- 新增 `<TimePicker />` 配置支持 [#638](https://github.com/XiaoMi/hiui/issues/638)
- 新增 `<Dropdown />` 多级数据支持 [#594](https://github.com/XiaoMi/hiui/issues/594)
- …
=> chore: update version and changelog

components/_util/depreactedPropsCompat.js, components/form/Form.js, components/form/Item.js
depreactedPropsCompat remove forwardref
=> chore: depreactedPropsCompat remove forwardref

components/_util/SwitchVersion.js, docs/demo/form/section-check.jsx
=> fix: switchversion (#708)

components/carousel/index.js, components/cascader/Cascader.js, components/pagination/Pagination.js, docs/demo/cascader/section-advanced.jsx, docs/zh-CN/components/cascader.mdx, docs/zh-CN/components/date-picker.mdx
fix #696  
fix #703 
fix #704 
fix #667 
fix #713
=> fix: #696 #703 #704 #667

components/date-picker/BasePicker.js, components/date-picker/dateUtil.js
=> Compatible date format

components/select/Select.js
=> fix: fix #737

components/cascader/Cascader.js, components/cascader/Menu.js
=> fix: fix #721

components/checkbox/CheckBox.js, package.json
=> fix: checkbox list do not change but rerender

components/button/Button.js, package.json
=> fix: fix #747

components/loading/Loading.js
=> fix: Loading error

components/locales/en-US.js, components/locales/zh-CN.js, components/upload/UploadDrag.js, components/upload/UploadPhoto.js
=> 变更:Upload 上传数量达到设定值时的展现状态

docs/demo/upload/section-ban.jsx, docs/demo/upload/section-default.jsx, docs/demo/upload/section-drag.jsx, docs/demo/upload/section-head.jsx, docs/demo/upload/section-picture-wall.jsx, docs/demo/upload/section-picture.jsx, docs/demo/upload/section-upload.jsx
=> update upload remote address

components/rate/Rate.js
=> fix: Rate props update

components/date-picker/BasePicker.js, components/date-picker/DatePicker.js, components/date-picker/DateRangePanel.js, components/date-picker/constants.js
=> fix: datepicker format error

components/style/icon/diyIcon.scss, components/upload/UploadPhoto.js, components/upload/UploadPictureCard.js, components/upload/style/index.scss
=> fix(upload):ui样式

components/card/style/index.scss, components/carousel/index.js, components/carousel/style/index.scss, docs/demo/carousel/section-icon.jsx, docs/zh-CN/components/carousel.mdx
=> fix: 走马灯指示器效果; fix: 卡片title样式#967

components/rate/Rate.js, components/rate/style/index.scss, components/tabs/Tabs.js, docs/demo/rate/section-advanced.jsx, docs/demo/rate/section-character.jsx, docs/demo/rate/section-face.jsx, docs/demo/rate/section-renderCharacter.jsx, docs/zh-CN/components/rate.mdx, docs/zh-CN/components/tabs.mdx
1.辅助文字
2.竖直方向半选
3.自定义字符
4.自定义渲染
=> feature:Rate

CHANGELOG.md, components/transfer/Item.js, components/transfer/Transfer.js, docs/demo/transfer/section-area.jsx, docs/zh-CN/components/transfer.mdx
=> fea:Transfer穿梭框新增拖拽事件

components/select-tree/components/Trigger.jsx, components/select-tree/components/tree/util.js
SelectTree: 微调异步多选报错问题修复 #1491
=> fix: SelectTree: 微调异步多选报错问题修复 #1491

CHANGELOG.md, components/checkbox/style/index.scss
=> fix: #1482

components/carousel/index.js, components/carousel/style/index.scss
=> feat: #1508

CHANGELOG.md, components/select-tree/SelectTreeHook.js, components/select/style/select-dropdown.scss, site/main.js
=> fix: #1519

components/popper/Overlay.js, components/popper/README.md
=> feat: popper docs

CHANGELOG.md, components/preview/index.d.ts, components/preview/index.js, components/preview/style/index.js, components/preview/style/index.scss, docs/demo/preview/section-base.jsx, docs/zh-CN/components/preview.mdx, site/locales/en-US.js, site/locales/zh-CN.js, site/pages/components/index.js
=> feat: #1546

.npmignore
=> chore: #1556

components/stepper/style/index.scss, docs/demo/stepper/section-vertical.jsx, package-lock.json
关联issue：https://github.com/XiaoMi/hiui/issues/1155
=> fix:修复stepper垂直状态下显示异常

CHANGELOG.md, components/switch/index.js
=> fix: #1566

CHANGELOG.md, components/date-picker/TimePicker.jsx, components/date-picker/components/Time.jsx, components/date-picker/components/TimeList.jsx, components/date-picker/components/TimePanel.jsx, components/date-picker/hooks/useCalenderData.js, docs/zh-CN/components/time-picker.mdx
=> fix: #1530

CHANGELOG.md, components/transfer/Item.js, components/transfer/Transfer.js, components/transfer/style/index.scss, docs/zh-CN/components/transfer.mdx
=> fix: #1575 #1576

docs/demo/preview/section-base.jsx, docs/zh-CN/components/preview.mdx
=> chore: popover demo

CHANGELOG.md, components/select/Select.js, components/select/SelectDropdown.js, docs/demo/select/section-async.jsx
=> fix: #1597

components/date-picker/BasePicker.jsx, components/popper/Overlay.js, components/popper/utils/useClickOutside.js, components/select/Select.js
=> feat: useClickOutside.setEventName

components/table/index.d.ts, components/upload/index.d.ts
=> chore: update interface

CHANGELOG.md, components/cascader/Menu.js
=> fix: #1648

components/upload/hooks/useUpload.js, components/upload/index.d.ts, components/upload/request.js, docs/demo/upload/section-custom.jsx, docs/demo/upload/section-drag.jsx, docs/demo/upload/section-head.jsx, docs/demo/upload/section-picture-wall.jsx, docs/demo/upload/section-picture.jsx, docs/demo/upload/section-upload.jsx
=> feat: #1685

CHANGELOG.md, components/form/Form.js, components/form/Item.js, docs/demo/form/section-check.jsx, docs/zh-CN/components/form.mdx
=> feat: #1691

CHANGELOG.md, components/date-picker/components/RangePanel.jsx, docs/zh-CN/docs/upgrade-from-2x.mdx
=> fix: #1688

CHANGELOG.md, docs/zh-CN/docs/changelog.mdx, package.json
=> chore: 3.6.0

CHANGELOG.md, components/slider/index.js, components/tooltip/index.js
=> fix: #1703 #1704

build/prerenderSite.js
=> build: path

CHANGELOG.md, docs/zh-CN/docs/changelog.mdx, package.json
=> build: #1719

CHANGELOG.md, docs/zh-CN/docs/changelog.mdx
=> chore: changelog

components/select-tree/SelectTreeHook.js, components/select-tree/components/tree/util.js
=> fix: SelectTree组件 defaultExpandAll属性不生效

CHANGELOG.md, components/form/Form.js, components/form/Item.js
=> feat: #1741

CHANGELOG.md, components/table/HeaderTable.jsx
=> fix: #1749

CHANGELOG.md, components/tree/Tree.js, docs/demo/tree/section-normal.jsx
=> fix: #1761

CHANGELOG.md, components/form/index.d.ts, components/table/Cell.jsx, components/table/index.d.ts, docs/zh-CN/components/table.mdx
=> feat: #1808

CHANGELOG.md, components/hi-request/download.ts
修复使用HiRequest，type='download'下载文件时，不能正确解析下载文件名中特殊字符的问题
=> fix: HiRequest在type='download'时不能正确解析filename问题

CHANGELOG.md, components/badge/index.d.ts, components/preview/index.d.ts, components/preview/index.js, docs/zh-CN/components/preview.mdx
=> fix: #1816

CHANGELOG.md, components/select-tree/SelectTreeHook.js, components/select-tree/components/tree/TreeNode.jsx, components/select-tree/components/tree/index.jsx, components/select-tree/components/tree/util.js, components/select-tree/style/index.scss, docs/demo/select-tree/section-filter.jsx
=> fix: #1791

CHANGELOG.md, components/carousel/index.js, components/date-picker/TimePicker.d.ts, components/date-picker/index.d.ts, components/select/index.d.ts
=> feat: #1834

CHANGELOG.md, components/date-picker/components/TimeList.jsx, components/table/BodyTable.jsx, components/table/HeaderTable.jsx
=> fix: #1844

CHANGELOG.md, components/form/Form.js, components/form/Item.js, components/form/SchemaForm.js, components/form/utils.js, docs/demo/form/section-schema.jsx, docs/zh-CN/components/form.mdx
=> fix: #1862

CHANGELOG.md, components/modal/index.d.ts, components/modal/index.jsx, docs/demo/modal/section-async.jsx, docs/zh-CN/components/modal.mdx
=> feat: #1866

CHANGELOG.md, components/form/Item.js, components/form/utils.js
=> fix: #1842

CHANGELOG.md, components/select-tree/SelectTreeHook.js, components/select-tree/components/tree/NavTree.js, components/select-tree/components/tree/TreeNode.jsx, components/select-tree/components/tree/style/index.scss, components/select-tree/components/tree/util.js, components/select-tree/index.d.ts, docs/demo/select-tree/section-bread.jsx, docs/demo/select-tree/section-multiple.jsx, docs/demo/select-tree/section-single.jsx, docs/zh-CN/components/select-tree.mdx
=> feat: #1870

components/tree/hooks/useSelect.js, components/tree/index.d.ts, docs/demo/tree/section-normal.jsx, docs/zh-CN/components/tree.mdx, package-lock.json
=> feat: add selectable for tree node

docs/zh-CN/components/alert.mdx
=> fix: update alert doc

components/transfer/Transfer.js
=> fix: 修改穿梭框input样式异常

docs/zh-CN/components/charts.mdx
=> chore: 修改文档

components/form/style/index.scss
=> fix: 修复 datepicker 表单验证样式异常

components/date-picker/components/Root.jsx, components/date-picker/hooks/usePlaceholder.js
=> fix: 修复 datepicker placeholder 字符串失效

components/cascader/index.d.ts
=> fix: cascader types

components/input/Input.js
=> fix: 修复 input 组件value 值不受控更新

components/form/Item.js, docs/demo/form/section-dynamic.jsx
=> fix: Form 组件添加对 rules 的受控

docs/demo/date-picker/section-date-time.jsx
修正时间选择器 日期时间 部分，Input 展示内容和选择内容不同步问题
resolve: #1965
=> 修正日期时间选择器demo问题

components/date-picker/BasePicker.jsx, components/date-picker/components/RangePanel.jsx, components/date-picker/components/Root.jsx, components/date-picker/hooks/useCalenderData.js, components/date-picker/hooks/useDate.js, components/date-picker/utils.js
=> fix: 修复 weekOffset周选择失效

components/input/index.d.ts, components/table/index.d.ts
=> fix: 修复类型定义

components/table/HeaderTable.jsx, components/table/Row.jsx, components/table/index.d.ts, docs/zh-CN/components/table.mdx
=> feat: #1988

CHANGELOG.md, components/dropdown/index.js
=> feat: close #1991

CHANGELOG.md, components/table/Row.jsx, components/table/Table.jsx
=> fix: close #1993

CHANGELOG.md, components/table/SettingMenu.jsx, components/table/Table.jsx, components/table/index.d.ts, docs/zh-CN/components/table.mdx, package-lock.json, package.json
=> feat: #1994

CHANGELOG.md, components/table/BodyTable.jsx, components/table/HeaderTable.jsx, components/table/Row.jsx, components/table/Table.jsx, components/table/index.d.ts, docs/demo/table/section-row.jsx, docs/demo/table/section-special.jsx, docs/zh-CN/components/table.mdx
=> feat: close #2007

components/table/AdvanceHeader/CustomFilter.js, components/table/AdvanceHeader/select/index.js, components/table/BodyTable.jsx, components/table/HeaderTable.jsx, components/table/Row.jsx, components/table/Table.jsx, components/table/util.js, package-lock.json, package.json
=> fix(table): close #2017

components/select/Select.js
=> opt(select): close #2020

components/form/Item.js
=> fix(form): SchemeForm initialValues 初始化值无法生效 #2028

components/carousel/index.js
=> fix: #2033

components/table/HeaderTable.jsx, components/table/Table.jsx
=> fix(table#2035):Table 组件拖拽到自身节点时，不应该触发删除当前拖动节点

components/form/Form.js, components/form/utils.js
=> fix(form): SchemeForm onValuesChange 返回数据字段异常 #2077

components/input/Input.js
=> fix(#2081): 修复 Safari Input 中文输入产生无效字符

packages/ui/date-picker/src/components/panel.tsx, packages/ui/date-picker/src/components/picker-icon.tsx, packages/ui/date-picker/src/components/root.tsx, packages/ui/time-picker/src/Input.tsx, packages/ui/time-picker/src/Selector.tsx, packages/ui/time-picker/src/TimePicker.tsx
- 修正 range 分割文案 “至“ -> ”-“
- 修正 range 模式下，大范围滚动之后，出现无限自循环滚动的问题
- 修正 图标
=> Next/4.0 date picker UI fix

components/input/Input.js
=> feat(input): add textarea ref export

components/table/Row.jsx, components/table/Table.jsx, components/table/index.d.ts, docs/zh-CN/components/table.mdx
=> feat(table#2093): 添加 onRow

components/form/utils.js
=> fix(form): close 2077

components/tree/Tree.js
=> fix(tree): 修复 contextMenu 为空时展示异常

components/date-picker/TimePicker.jsx, components/progress/index.d.ts, components/tree/hooks/useSelect.js
=> Hotfix#2131

packages/ui/descriptions/src/Descriptions.tsx, packages/ui/descriptions/src/styles/descriptions.scss, packages/ui/descriptions/stories/no-background.stories.tsx
=> fix: change descriptions api

components/checkbox/style/index.scss, components/table/HeaderTable.jsx, components/table/style/index.scss
=> fix(table#2139)

components/form/Item.js
=> fix(form#2141)

components/collapse/Panel.jsx, components/collapse/index.d.ts, components/collapse/index.js, docs/zh-CN/components/collapse.mdx
=> feat(collapse#2147): add className and style support

components/input/style/index.scss, components/modal/index.d.ts, components/modal/index.jsx, docs/zh-CN/components/modal.mdx
=> feat: add modalContentRef for Modal

docs/demo/select/section-async.jsx
Select.dataSource.type->method
=> fix: 修复select组建异步示例代码问题

packages/ui/progress/src/Progress.tsx
=> fix(progress): show numerical overflow percent is 56

CONTRIBUTING.md, packages/ui/space/src/Space.tsx, packages/ui/space/src/styles/space.scss
=> fix: 修复item宽度样式问题

packages/ui/hiui/package.json, packages/ui/space/package.json
- @hi-ui/hiui@4.0.8
- @hi-ui/space@4.0.2
=> chore(release): publish %v

packages/ui/table/src/TableBody.tsx, packages/ui/table/src/use-table.ts
=> fix(table): fix scrollWidth not work

packages/ui/hiui/package.json, packages/ui/hiui/src/index.ts
合并 Scrollbar InputGroup Anchor BackTop 组件
=> feat(hiui): 合并新组建

packages/ui/date-picker/src/components/calendar.tsx, packages/ui/date-picker/src/types.ts
closed #2217 
1.修复V4版本中日历节气显示问题
=> fix(date-picker): 修复节气显示问题

packages/ui/card/src/styles/card.scss
=> fix(card): 修复子卡片样式污染问题

packages/ui/pop-confirm/src/use-pop-confirm.ts, packages/ui/pop-confirm/stories/gutter-gap.stories.tsx, packages/ui/pop-confirm/stories/index.stories.tsx, packages/ui/popover/src/use-popover.tsx, packages/ui/popover/stories/gutter-gap.stories.tsx, packages/ui/popover/stories/index.stories.tsx, packages/ui/tooltip/src/use-tooltip.ts, packages/ui/tooltip/stories/gutter-gap.stories.tsx, packages/ui/tooltip/stories/index.stories.tsx
closed #2223 
曾加 API：gutterGap
=> feat(popover): 增加设置间距功能

packages/ui/modal/src/Modal.tsx, packages/ui/modal/src/styles/modal.scss
=> fix(modal): 修改max-height值的设定

packages/ui/form/src/styles/form.scss
=> fix(form): 修复内嵌FormItem样式污染问题

packages/ui/tree/src/use-tree-search.tsx
=> feat(tree): 自定义搜索增加多个key匹配

packages/ui/menu/src/MenuItem.tsx
=> fix(menu): 修复onClick回调函数参数问题

packages/ui/date-picker/src/styles/date-picker.scss, packages/ui/input/src/styles/input.scss, packages/ui/input/src/styles/mock-input.scss, packages/ui/textarea/src/styles/textarea.scss, packages/ui/time-picker/src/styles/input.scss
closed #2266 
修改点：
1.在unset模式下，将控件的placeholder字体颜色设置为 G50
=> fix(date-picker time-picker input textarea): #2266

packages/ui/switch/src/Switch.tsx, packages/ui/switch/src/styles/switch.scss, packages/ui/switch/stories/basic.stories.tsx, packages/ui/switch/stories/custom.stories.tsx, packages/ui/switch/stories/index.stories.tsx, packages/ui/switch/stories/size.stories.tsx
=> feat(switch): add size api

.changeset/eleven-buses-glow.md, .changeset/heavy-goats-wonder.md, packages/ui/check-select/src/CheckSelect.tsx, packages/ui/check-select/stories/custom-render.stories.tsx, packages/ui/check-select/stories/index.stories.tsx, packages/ui/table/stories/custom-filter.stories.tsx
=> feat(check-select): 增加customRender api

.changeset/cold-planes-develop.md, packages/ui/table/src/TableBody.tsx, packages/ui/table/src/styles/table.scss
=> fix(table): #2314

.changeset/twelve-weeks-carry.md, packages/ui/date-picker/src/DatePicker.tsx
=> fix(date-picker): #2311

.changeset/fresh-apes-cheat.md, .changeset/shy-boxes-explode.md, packages/ui/tabs/src/TabList.tsx, packages/ui/tabs/src/styles/tabs.scss
=> fix(tabs): #2323

.changeset/eight-readers-perform.md, .changeset/old-plants-sing.md, packages/ui/date-picker/src/DatePicker.tsx
=> fix(date-picker): #2325

components/date-picker/BasePicker.jsx, components/date-picker/components/Time.jsx, package-lock.json, package.json
=> fix(date-picker): #2328

components/select/style/select-input.scss
=> fix(select): #2331

.changeset/curvy-bobcats-look.md, .changeset/shaggy-falcons-peel.md, packages/ui/table/src/hooks/use-check.ts, packages/ui/table/src/types.ts, packages/ui/table/stories/row-selection.stories.tsx
=> feat(table): #2317

.changeset/curvy-hounds-pump.md, .changeset/itchy-pianos-lie.md, packages/ui/check-select/src/CheckSelect.tsx, packages/ui/check-tree-select/src/CheckTreeSelect.tsx, packages/ui/select/src/Select.tsx, packages/ui/tree-select/src/TreeSelect.tsx
=> fix(Select): #2333

.changeset/hip-comics-shake.md, .changeset/soft-rats-sip.md, packages/ui/form/src/FormList.tsx, packages/ui/form/src/types.ts, packages/ui/form/stories/list.stories.tsx
=> feat(form): #2335

packages/ui/hiui/package.json, packages/ui/hiui/src/index.ts, packages/ui/loading/package.json, packages/ui/loading/src/Loading.tsx, packages/ui/loading/src/use-loading.ts, packages/ui/loading/stories/index.stories.tsx, packages/ui/loading/stories/indicator.stories.tsx, packages/ui/loading/stories/type.stories.tsx, packages/ui/spinner/src/Spinner.tsx, packages/ui/spinner/src/styles/spinner.scss, packages/ui/spinner/stories/basic.stories.tsx, packages/ui/spinner/stories/index.stories.tsx, packages/ui/spinner/stories/size.stories.tsx
closed #2256 
1.增加 Spinner 组件，支持设置大小
2.和 Loading 组件结合，支持局部显示loading效果
=> feat(spinner&loading): 增加环形loading组件

.changeset/itchy-brooms-sell.md, .changeset/wet-pugs-juggle.md, packages/ui/tree/src/use-tree-search.tsx, packages/ui/tree/stories/custom-search.stories.tsx
=> feat(tree): #2350

.changeset/olive-doors-wash.md, .changeset/purple-pans-accept.md, packages/ui/tree/src/use-tree-search.tsx
=> fix(tree): #2353

packages/ui/ellipsis-tooltip/src/EllipsisTooltip.tsx, packages/ui/ellipsis-tooltip/stories/index.stories.tsx, packages/ui/ellipsis-tooltip/stories/max-text-count.stories.tsx
=> chore(ellipsis-tooltip): 代码完善

.changeset/eleven-peas-smile.md, .changeset/twenty-rocks-hammer.md, packages/ui/form/src/FormLabel.tsx, packages/ui/form/stories/label-placement.stories.tsx
=> fix(form): #2373

.changeset/breezy-schools-burn.md, packages/core/core-css/src/styles/common/helper.scss
=> fix(core-css): #2377

.changeset/seven-rivers-tickle.md, .changeset/slimy-schools-float.md, packages/ui/modal/src/Modal.tsx, packages/ui/modal/src/use-modal.ts
=> fix(modal): #2375

.changeset/swift-kings-pull.md, .changeset/wild-seals-bathe.md, packages/ui/menu/src/Menu.tsx, packages/ui/menu/src/MenuItem.tsx, packages/ui/menu/src/context.ts
=> feat(menu): #2382

.changeset/curly-goats-hug.md, .changeset/smooth-oranges-grab.md, packages/ui/pagination/src/PagerButton.tsx
ShrinkPagination 组件中调用了 useCounter hook，返回的 getPlusButtonProps 和 getMinusButtonProps 方法，调用后返回的对象中有 ref 属性，如果 PagerButton 组件中没有对外配置 ref，当使用返回的对象时，控制台会报错。
=> hotfix(pagination): 给 PagerButton 组件提供 ref 属性

.changeset/beige-papayas-type.md, .changeset/fast-rockets-cheer.md, packages/ui/tree/src/Tree.tsx, packages/ui/tree/src/TreeNode.tsx, packages/ui/tree/src/context.ts, packages/ui/tree/stories/expand-on-click.stories.tsx, packages/ui/tree/stories/index.stories.tsx
=> feat(tree): #2397

.changeset/fast-islands-notice.md, .changeset/nice-rivers-repair.md, packages/ui/check-select/src/CheckSelect.tsx, packages/ui/select/src/Select.tsx
=> fix(select、check-select): #2404

.changeset/flat-buses-hide.md, .changeset/hip-trees-wave.md, packages/ui/modal/src/Modal.tsx
=> fix(modal): #2402

.changeset/gold-mails-compare.md, .changeset/wild-dragons-leave.md, packages/ui/slider/src/Slider.tsx, packages/ui/slider/src/use-slider.ts, packages/ui/tooltip/src/Tooltip.tsx, packages/ui/tooltip/src/types.ts, packages/ui/tooltip/src/use-tooltip.ts
=> fix(slider): #2415

.changeset/tiny-shrimps-deliver.md, .changeset/violet-mugs-work.md, packages/ui/upload/src/AvatarUpload.tsx, packages/ui/upload/src/utils.ts
=> fix(upload): #2418

.changeset/brown-berries-arrive.md, .changeset/thick-weeks-clean.md, packages/ui/date-picker/src/components/panel.tsx, packages/ui/date-picker/stories/basic.stories.tsx
=> fix(date-picker): #2422

components/date-picker/components/Time.jsx, components/date-picker/utils.js, package-lock.json, package.json
=> fix(date-picker): #2420

.changeset/cyan-cooks-fold.md, .changeset/silent-dolphins-compete.md, packages/ui/upload/src/hooks/use-upload.ts
=> fix(upload): #2426

.changeset/shaggy-bananas-explode.md, .changeset/young-buttons-enjoy.md, packages/ui/upload/src/DragUpload.tsx, packages/ui/upload/src/hooks/use-upload.ts, packages/ui/upload/src/utils.ts, packages/ui/upload/stories/draggable.stories.tsx
=> fix(upload): #2442

.changeset/odd-lobsters-juggle.md, .changeset/strong-grapes-cover.md, packages/ui/input/package.json, packages/ui/input/src/use-input-cursor.ts
=> fix(input): #2446

.changeset/great-cobras-beam.md, .changeset/tidy-geese-trade.md, packages/ui/table/src/styles/table.scss, packages/ui/table/stories/custom-filter.stories.tsx
=> fix(table): #2450

.changeset/little-bananas-remain.md, .changeset/little-melons-refuse.md, packages/ui/table/src/Table.tsx, packages/ui/table/src/TableSettingMenu.tsx, packages/ui/table/src/types.ts, packages/ui/table/stories/setting.stories.tsx
=> feat(table): #2452

.changeset/gorgeous-experts-listen.md, .changeset/great-buses-punch.md, packages/ui/date-picker/src/components/range-panel.tsx
=> fix(date-picker): #2457

.changeset/moody-berries-wait.md, .changeset/wet-buses-do.md, packages/ui/ellipsis-tooltip/src/EllipsisTooltip.tsx
=> fix(ellipsis-tooltip): type error

.changeset/cool-lies-wait.md, .changeset/serious-beers-hang.md, packages/ui/time-picker/src/TimePicker.tsx
=> fix(time-picker): #2463

.changeset/eleven-pumas-taste.md, .changeset/mean-dancers-stare.md, packages/ui/counter/src/Counter.tsx, packages/ui/counter/src/use-counter.ts, packages/ui/number-input/stories/formatter.stories.tsx, packages/ui/number-input/stories/index.stories.tsx
=> feat(counter&number-input): #2386

.github/workflows/scan.yml
https://sonarcloud.io/project/configuration?id=hiui-components
=> build: add sonarcloud scan

.github/workflows/scan.yml
=> feat: update scan config

.changeset/big-horses-march.md, .changeset/rare-berries-sit.md, packages/ui/anchor/src/use-anchor.ts, packages/ui/table/src/TableBody.tsx, packages/ui/table/src/hooks/use-col-frozen.ts, packages/ui/table/src/hooks/use-colgroup.ts, packages/ui/table/stories/data-sorter.stories.tsx, packages/ui/tree/src/TreeNode.tsx, packages/ui/tree/src/hooks/use-drag.ts, packages/ui/tree/src/hooks/use-focus.ts, packages/ui/tree/src/use-tree-action.tsx, packages/ui/upload/src/AvatarUpload.tsx, packages/ui/upload/src/DragUpload.tsx, packages/ui/upload/src/hooks/use-upload.ts
=> fix: scan bugs

.changeset/early-lobsters-heal.md, .changeset/friendly-walls-sell.md, packages/ui/date-picker/src/hooks/useTimePickerFormat.ts
=> fix(date-picker): #2479

.changeset/honest-pianos-fly.md, .changeset/lazy-roses-bathe.md, packages/ui/check-select/src/CheckSelect.tsx, packages/ui/select/src/Select.tsx
=> fix(selct&check-select): #2480

.changeset/kind-llamas-add.md, .changeset/silver-onions-explain.md, packages/ui/counter/src/Counter.tsx, packages/ui/counter/src/use-counter.ts, packages/ui/counter/stories/controlled.stories.tsx, packages/ui/number-input/stories/controlled.stories.tsx, packages/ui/number-input/stories/formatter.stories.tsx
closed #2488 
增加了对 null 值的处理,当值设置为 null 时输入框显示为空
=> fix(counter): #2488

.changeset/rude-beds-bake.md, .changeset/wet-taxis-jam.md, packages/ui/dropdown/src/Dropdown.tsx, packages/ui/dropdown/src/styles/dropdown.scss
closed #2490 
增加 dataItem 设置 disable 后样式
=> fix(dropdown): #2490

.changeset/curvy-crabs-brush.md, .changeset/tender-rats-exist.md, packages/ui/drawer/src/Drawer.tsx, packages/ui/drawer/src/styles/drawer.scss
=> fix(drawer): #2494

.changeset/early-dolls-destroy.md, .changeset/early-wasps-crash.md, packages/ui/counter/src/Counter.tsx, packages/ui/counter/src/use-counter.ts, packages/ui/number-input/stories/formatter.stories.tsx
=> fix(counter&number-input): #2496

.changeset/brave-dodos-sip.md, .changeset/odd-pumpkins-glow.md, packages/ui/tree/src/Tree.tsx, packages/ui/tree/src/styles/tree.scss, packages/ui/tree/stories/custom-title.stories.tsx, packages/ui/tree/stories/index.stories.tsx, packages/ui/tree/stories/size.stories.tsx
=> feat(tree): #2503

.changeset/chilled-apes-cry.md, .changeset/great-bears-sparkle.md, packages/ui/tree/src/use-tree-search.tsx, packages/ui/tree/stories/custom-search.stories.tsx
=> feat(tree): #2511

package.json, packages/ui/cascader/stories/filter-options.stories.tsx, packages/ui/check-select/stories/pinyin.stories.tsx, packages/ui/select/package.json, packages/ui/select/stories/pinyin.stories.tsx, packages/utils/env/package.json, scripts/hi-build/lib/build.js, scripts/hi-build/package.json, yarn.lock
1.stories 中的拼音库改为 pinyin-pro
2.去掉 inject-head-style 依赖
=> fix: security scan

.changeset/purple-poets-complain.md, .changeset/tidy-bikes-drum.md, packages/ui/check-tree-select/package.json, packages/ui/check-tree-select/src/CheckTreeSelect.tsx, packages/ui/check-tree-select/src/utils/index.ts, packages/ui/check-tree-select/stories/check-all.stories.tsx, packages/ui/check-tree-select/stories/index.stories.tsx
=> feat(check-tree-select): #2515

components/search/index.js, package.json
=> fix(search): v3 #2524

components/date-picker/BasePicker.jsx
=> hotfix(date-picker): v3 #2525

.changeset/big-apricots-work.md, .changeset/fifty-cycles-jam.md, packages/ui/textarea/src/styles/textarea.scss
closed #2533 
修复 resize 调整高度和 disabled 样式问题
=> fix: #2533

.changeset/orange-colts-brush.md, .changeset/slimy-walls-wash.md, packages/ui/counter/src/use-counter.ts, packages/ui/number-input/src/styles/number-input.scss, packages/ui/number-input/stories/basic.stories.tsx
closed #2537 
NumberInput 支持 placeholder
=> feat(counter&number-input): #2537

packages/ui/descriptions/src/Descriptions.tsx
=> fix(descriptions): bugfix

.changeset/short-mice-move.md, .changeset/ten-toys-wonder.md, packages/ui/menu/src/Menu.tsx
修复问题：
1.菜单收起时会显示2个图标
2.菜单收起时再次打开，会有子菜单弹出层闪现一次
=> fix(menu): 体验优化

.changeset/little-masks-argue.md, .changeset/strange-flies-switch.md, packages/ui/collapse/src/styles/collapse-panel.scss
=> fix(collapse): #2546

.changeset/olive-dancers-invent.md, .changeset/pink-snakes-lay.md
=> chore(descriptions): 添加变更记录文件

.changeset/nice-berries-turn.md, .changeset/three-mirrors-leave.md, packages/ui/upload/src/styles/upload.scss, packages/ui/upload/src/utils.ts, packages/ui/upload/stories/draggable.stories.tsx
closed #2549 
修改点：
1.accept 支持 .文件类型 这类格式，可以兼容 Windows 下限制选择其他文件
2.修复删除按钮没有垂直居中样式问题
=> fix(upload): #2549

.changeset/slow-humans-drive.md, .changeset/strong-feet-invite.md, packages/ui/preview/src/Preview.tsx, packages/ui/preview/src/styles/preview.scss, packages/ui/preview/stories/index.stories.tsx, packages/ui/preview/stories/multiple.stories.tsx
=> feat(preview): #2541

.changeset/long-starfishes-relate.md, .changeset/orange-brooms-shave.md, .changeset/rude-moles-unite.md, packages/ui/table/src/use-table.ts, packages/ui/table/stories/table-tree.stories.tsx, packages/utils/tree-utils/src/index.ts
=> feat(table): #2556

packages/ui/table/src/TableBody.tsx, packages/ui/table/src/types.ts, packages/ui/table/src/use-table.ts, packages/ui/table/stories/virtual.stories.tsx
=> fix(table): virtual maxHeight error

.changeset/nice-swans-add.md, .changeset/pink-crabs-vanish.md, packages/ui/date-picker/src/DatePicker.tsx, packages/ui/date-picker/src/types.ts
=> feat(date-picker): #2565

.changeset/moody-jars-admire.md, .changeset/smooth-phones-build.md, packages/ui/menu/src/Menu.tsx, packages/ui/menu/src/MenuItem.tsx, packages/ui/menu/stories/index.stories.tsx, packages/ui/menu/stories/render.stories.tsx, packages/ui/popper/src/Popper.tsx, packages/ui/popper/src/styles/popper.scss
=> feat(menu&popper): #2575

.changeset/cool-tables-check.md, .changeset/green-peas-deny.md, .changeset/tasty-pets-care.md, packages/ui/menu/src/Menu.tsx, packages/ui/menu/src/MenuItem.tsx, packages/ui/menu/src/styles/menu.scss, packages/ui/menu/stories/index.stories.tsx, packages/ui/menu/stories/size.stories.tsx
=> feat(menu): 增加 size API

packages/ui/hiui/package.json, packages/ui/hiui/src/index.ts, packages/ui/table/src/hooks/use-col-width.ts
ResizeBox 暂时不发版，hiui 合包中暂时去掉，同时修改了一个 Table 类型问题。
=> fix(hiui): remove resizebox

.changeset/light-pumas-arrive.md, .changeset/perfect-dolls-float.md, packages/ui/collapse/src/Collapse.tsx, packages/ui/collapse/src/styles/collapse-panel.scss, packages/ui/collapse/stories/index.stories.tsx, packages/ui/collapse/stories/size.stories.tsx, packages/ui/collapse/stories/title.stories.tsx
=> feat(collapse): size 增加 sm 尺寸

packages/ui/list/stories/avatar.stories.tsx, scripts/hi-docs/src/parse-stories.mjs
1.构建组件文档示例时，去掉对stories代码的格式化。
2.修改 List 组件中 Avatar stories 代码写法。
=> chore(hi-docs): 修改stories格式化

.changeset/flat-insects-smoke.md, .changeset/selfish-islands-double.md, packages/ui/descriptions/src/Descriptions.tsx, packages/ui/descriptions/src/styles/descriptions.scss, packages/ui/descriptions/stories/index.stories.tsx, packages/ui/descriptions/stories/size.stories.tsx
=> feat(descriptions): add size api

.changeset/gentle-doors-design.md, .changeset/metal-fireants-sneeze.md, packages/ui/check-cascader/src/CheckCascader.tsx, packages/ui/check-cascader/src/styles/check-cascader.scss, packages/ui/check-cascader/stories/index.stories.tsx, packages/ui/check-cascader/stories/size.stories.tsx
=> Feature/check cascader(add size api)

.changeset/proud-turkeys-call.md, .changeset/spotty-tools-cross.md, packages/ui/cascader/src/Cascader.tsx, packages/ui/cascader/src/styles/cascader.scss, packages/ui/cascader/stories/index.stories.tsx, packages/ui/cascader/stories/size.stories.tsx
=> feat(cascader): add size api

.changeset/afraid-guests-smoke.md, .changeset/red-plants-sleep.md, packages/ui/cascader/src/CascaderMenuList.tsx, packages/ui/check-cascader/src/CheckCascader.tsx, packages/ui/check-cascader/src/CheckCascaderMenu.tsx, packages/ui/check-cascader/src/CheckCascaderMenuList.tsx, packages/ui/check-cascader/stories/dropdown-column-render.stories.tsx, packages/ui/check-cascader/stories/footer.stories.tsx, packages/ui/check-cascader/stories/index.stories.tsx
=> feat(check-cascader): #2595

.changeset/flat-chicken-speak.md, .changeset/three-bees-explain.md, packages/ui/tree/src/hooks/use-expand.ts
=> fix(tree): #2598

packages/ui/badge/src/Badge.tsx, packages/ui/badge/stories/color.stories.tsx
=> fix(badge): #2616

.changeset/mighty-foxes-jog.md, .changeset/shiny-foxes-attack.md, packages/ui/descriptions/src/styles/descriptions.scss
=> fix(descriptions): #2619

.changeset/eighty-terms-agree.md, .changeset/funny-peaches-carry.md, packages/ui/date-picker/src/DatePicker.tsx, packages/ui/date-picker/src/components/calendar.tsx, packages/ui/date-picker/src/components/input.tsx, packages/ui/date-picker/src/components/panel.tsx, packages/ui/date-picker/src/components/range-panel.tsx, packages/ui/date-picker/src/components/root.tsx, packages/ui/date-picker/src/hooks/useCalenderData.tsx, packages/ui/date-picker/src/hooks/useData.ts, packages/ui/date-picker/src/types.ts, packages/ui/date-picker/src/utils/index.tsx, packages/ui/date-picker/stories/cell-render.stories.tsx
closed #2621 
增加 strideSelectMode API（用于控制跨月选择周范围时的交互方式） & format 支持函数
=> feat(date-picker): #2621

.changeset/blue-glasses-nail.md, .changeset/silent-lions-yawn.md, packages/ui/table/src/TheadContent.tsx, packages/ui/table/src/hooks/use-col-width.ts, packages/ui/table/src/use-table.ts, packages/ui/table/stories/custom-filter.stories.tsx, packages/ui/table/stories/resizable.stories.tsx
closed #2639 
可调整的最小列宽不超过标题内容宽度
=> perf(table): 优化resizable模式下可调整的最小列宽 (#2639)

.changeset/sharp-pots-clap.md, .changeset/thirty-oranges-brush.md, packages/ui/cascader/stories/dropdown-column-render.stories.tsx, packages/ui/check-cascader/stories/dropdown-column-render.stories.tsx, packages/ui/pop-confirm/src/use-pop-confirm.ts, packages/ui/pop-confirm/stories/index.stories.tsx, packages/ui/pop-confirm/stories/placement.stories.tsx
=> feat(pop-confirm): add placement api (#2640)

.changeset/large-shrimps-tap.md, .changeset/quiet-rings-film.md, .changeset/real-cheetahs-speak.md, packages/core/core-css/src/styles/tokens/color.scss
=> Hotfix/core css(#2636)

.changeset/lucky-owls-laugh.md, .changeset/strange-nails-sniff.md, packages/ui/alert/stories/duration.stories.tsx, packages/ui/tag/src/TagGroup.tsx, packages/ui/tag/stories/editor-render.stories.tsx, packages/ui/tag/stories/index.stories.tsx
=> feat(tag): add editorRender api (#2657)

package.json, packages/icons/stats.html, packages/ui/date-picker/stats.html, packages/ui/table/stats.html, packages/ui/upload/stats.html, scripts/hi-build/lib/build.js, scripts/hi-build/lib/cmd.js, scripts/hi-build/package.json, yarn.lock
1.将rollup升级到v3版本；
2.rollup配置中增加包分析功能；
3.对体积较大的组件进行包体积分析：Table、DatePicker、Upload、Icons
=> build: upgrade rollup3

.changeset/proud-tools-buy.md, .changeset/thin-ladybugs-joke.md, packages/ui/radio/src/RadioGroup.tsx, packages/ui/radio/src/styles/radio.scss, packages/ui/radio/stories/auto-width.stories.tsx, packages/ui/radio/stories/index.stories.tsx
=> feat(radio): feat: add autoWidth api (#2662)

.changeset/six-toys-grow.md, .changeset/stupid-cobras-exist.md, packages/ui/pop-confirm/src/PopConfirm.tsx, packages/ui/pop-confirm/src/styles/pop-confirm.scss, packages/ui/pop-confirm/stories/custom-content.stories.tsx, packages/ui/pop-confirm/stories/index.stories.tsx
=> feat(pop-confirm): add content api (#2666)

.changeset/afraid-falcons-decide.md, .changeset/heavy-panthers-care.md, packages/ui/modal/hi-docs.config.mdx, packages/ui/modal/src/with-api.tsx, packages/ui/modal/stories/with-api.stories.tsx
=> fix(modal): 补充 api 调用中的参数类型声明 (#2665)

.changeset/loud-pugs-work.md, .changeset/smart-paws-bow.md, packages/ui/picker/src/styles/picker.scss
closed #2676 
固定下拉框 box-sizing: content-box，否则其盒模型会受到外部影响，导致样式问题
=> fix(picker): 下拉框盒模型设置为 content-box (#2676)

.changeset/good-jobs-vanish.md, .changeset/old-falcons-lay.md, packages/ui/scrollbar/src/Scrollbar.tsx, packages/ui/scrollbar/src/styles/scrollbar.scss
=> feat(scrollbar): add zIndex api (#2687)

.changeset/angry-teachers-dream.md, .changeset/plenty-pillows-arrive.md, packages/ui/loading/src/Loading.tsx
closed #2696 
增加 wrapperClassName 和 wrapperStyle api
=> feat(loading): #2696

.changeset/fluffy-taxis-act.md, .changeset/modern-ducks-leave.md, .changeset/moody-balloons-glow.md, .changeset/seven-mice-switch.md, .changeset/tiny-shirts-divide.md, packages/ui/menu/src/MenuItem.tsx, packages/ui/menu/src/Sidebar.tsx, packages/ui/menu/src/index.ts, packages/ui/menu/src/styles/index.scss, packages/ui/menu/src/styles/sidebar.scss, packages/ui/menu/src/util.ts, packages/ui/menu/stories/index.stories.tsx, packages/ui/menu/stories/sidebar.stories.tsx, packages/ui/search/src/Search.tsx, packages/ui/search/src/SearchDropdown.tsx, packages/ui/search/stories/data.stories.tsx, packages/utils/tree-utils/src/index.ts
=> feat(menu): 增加侧边栏风格菜单

.changeset/poor-apples-repair.md, .changeset/silent-geckos-sell.md, packages/ui/checkbox/src/CheckboxGroup.tsx
=> fix(checkbox): 修复 null 传值问题 (#2716)

.changeset/chilly-cherries-float.md, .changeset/mighty-peaches-deliver.md, packages/ui/modal/hi-docs.config.mdx, packages/ui/modal/src/with-api.tsx
=> feat(modal): api 增加 close 方法和 key 参数 (#2709)

.changeset/fair-vans-remember.md, .changeset/violet-needles-train.md, packages/ui/check-tree-select/src/CheckTreeSelect.tsx, packages/ui/check-tree-select/stories/custom-render.stories.tsx, packages/ui/check-tree-select/stories/index.stories.tsx
=> feat(check-tree-select): add customRender api (#2731)

.changeset/curly-parents-work.md, .changeset/lazy-pets-film.md, packages/ui/carousel/src/Arrows.tsx, packages/ui/carousel/src/Carousel.tsx, packages/ui/carousel/src/Dots.tsx, packages/ui/carousel/src/types.ts
=> feat(carousel): add onIndexChange api (#2728)

.changeset/lucky-dots-speak.md, .changeset/thin-vans-float.md, packages/ui/check-cascader/src/hooks/use-check.ts
=> fix(check-cascader): 修复 PARENT 和 CHILD 模式在搜索场景下 id 丢失问题 (#2750)

.changeset/sour-suns-mate.md, .changeset/thirty-walls-fail.md, packages/ui/date-picker/src/DatePicker.tsx, packages/ui/date-picker/src/components/date-range-time-panel.tsx, packages/ui/date-picker/src/types.ts
=> feat(date-picker): add onOpen api (#2749)

.changeset/kind-singers-share.md, .changeset/red-beers-guess.md, packages/ui/check-select/src/CheckSelect.tsx, packages/ui/check-select/stories/addon.stories.tsx, packages/ui/check-select/stories/index.stories.tsx, packages/ui/tag-input/src/TagInputMock.tsx, packages/ui/tag-input/src/styles/tag-input-mock.scss
=> feat(tag-input&check-select): add prefix and suffix api (#2743)

.changeset/five-masks-shave.md, .changeset/hip-dryers-beam.md, packages/ui/input/src/MockInput.tsx, packages/ui/input/src/styles/mock-input.scss, packages/ui/input/stories/index.stories.tsx, packages/ui/select/src/Select.tsx, packages/ui/select/stories/addon.stories.tsx, packages/ui/select/stories/display-render.stories.tsx, packages/ui/select/stories/index.stories.tsx
=> feat(input&select): add prefix and suffix api

.changeset/eleven-boxes-battle.md, .changeset/honest-seas-lay.md, packages/ui/table/src/hooks/use-col-sorter.ts
=> fix(table): 修复 SettingDrawer 列更新问题 (#2754)

.changeset/fresh-bananas-double.md, .changeset/ninety-colts-heal.md, packages/ui/table/src/TableBody.tsx
=> fix(table): 修复 Safari 中设置 virtual 后只能表头滚动问题 (#2758)

.changeset/itchy-pigs-promise.md, .changeset/poor-camels-protect.md, packages/ui/date-picker/src/components/root.tsx
=> fix(date-picker): 修复受控模式下设置 showTime 后交互和界面问题 (#2757)

.changeset/ten-brooms-leave.md, .changeset/wild-wasps-sin.md, packages/ui/ellipsis-tooltip/src/EllipsisTooltip.tsx
=> fix(ellipsis-tooltip): 修复在下拉框中使用无效果问题 (#2764)

.changeset/lemon-buses-peel.md, .changeset/shaggy-swans-doubt.md, packages/ui/ellipsis-tooltip/src/EllipsisTooltip.tsx
=> fix(ellipsis-tooltip): 修复在 Table 中 resizable 模式下不显示气泡问题 (#2770)

.changeset/giant-gorillas-itch.md, .changeset/khaki-parrots-yell.md, packages/ui/space/src/Space.tsx
=> fix(space): 处理子节点为 null 情况 (#2774)

.changeset/chilled-jokes-hope.md, .changeset/mighty-tips-flow.md, packages/ui/list/src/List.tsx, packages/ui/list/stories/empty.stories.tsx
=> fix(list): emptyContent 只能修改文字无法修改图标 (#2776)

.changeset/rotten-beers-exercise.md, .changeset/stupid-dragons-boil.md, packages/ui/menu/src/Sidebar.tsx, packages/ui/menu/src/styles/sidebar.scss
=> fix(menu): 美化 Windows 中 sidebar 风格菜单滚动条样式 (#2782)

packages/ui/menu/package.json
=> chore(menu): 添加依赖

.changeset/nice-humans-sort.md, .changeset/young-donkeys-kiss.md, packages/ui/check-select/src/CheckSelect.tsx
closed: 修复CheckSelect组件onClear设置后没触发的问题
=> fix(check-select): 修复onClear设置后没触发(#2793)

.changeset/brown-mails-accept.md, .changeset/fast-waves-explode.md, packages/ui/pop-confirm/src/use-pop-confirm.ts
=> fix(pop-confirm): 修复点击确定按钮触发onCancel问题(#2810)

.changeset/clean-crabs-work.md, .changeset/light-nails-pull.md, packages/ui/table/src/hooks/use-col-width.ts
=> fix(table): 修复 columns 中将 title 设置为空字符串报错 (#2835)

packages/ui/table/stories/basic.stories.tsx, yarn.lock
将 package-lock.json 文件中 registry.nlark.com（该域名已下线） 改为 registry.npmmirror.com
=> chore: Update registrary.nlark.com in the package-lock file

.changeset/beige-actors-push.md, .changeset/dry-jokes-work.md, packages/ui/time-picker/src/TimePicker.tsx
=> fix(time-picker): 修复设置空字符串无效问题 (#2837)

.changeset/friendly-files-sit.md, .changeset/old-ears-greet.md, packages/ui/pagination/src/PageOption.tsx
=> fix(pagination): 每页显示条数选择器改为基于父元素定位 (#2865)

.changeset/grumpy-owls-cover.md, .changeset/nice-taxis-help.md, packages/ui/check-cascader/src/CheckCascader.tsx
=> feat(check-cascader): 支持配置字段别名

.changeset/many-flies-greet.md, .changeset/plenty-monkeys-end.md, packages/ui/tree-select/src/TreeSelect.tsx, packages/ui/tree-select/stories/basic.stories.tsx
=> feat(tree-select): 支持前缀后缀内容

.changeset/fresh-waves-act.md, .changeset/lovely-queens-sing.md, .changeset/pretty-queens-dress.md, .changeset/thin-sheep-leave.md, packages/ui/cascader/src/Cascader.tsx, packages/ui/check-cascader/src/CheckCascader.tsx, packages/ui/check-cascader/stories/addon.stories.tsx, packages/ui/check-cascader/stories/index.stories.tsx
=> feat(cascader): 支持前缀后缀内容

.changeset/strong-dragons-ring.md, .changeset/yellow-bats-argue.md, packages/ui/drawer/src/Drawer.tsx
=> feat(drawer): 支持自定义zIndex功能

.changeset/rich-guests-check.md, .changeset/thirty-apricots-count.md, packages/ui/check-tree-select/src/CheckTreeSelect.tsx, packages/ui/check-tree-select/stories/addon.stories.tsx, packages/ui/check-tree-select/stories/index.stories.tsx
=> feat(check-tree-select): 新增前缀后缀内容扩展(#2877)

.changeset/olive-mails-grin.md, .changeset/soft-cobras-film.md, packages/ui/search/src/Search.tsx, packages/ui/search/src/util.ts
=> feat(search): 支持配置字段别名(#2886)

.changeset/rich-geckos-study.md, .changeset/young-grapes-melt.md, packages/ui/filter/src/use-filter.ts, packages/ui/filter/src/utils.ts
=> feat(filter): 支持配置字段别名(#2915)

.changeset/selfish-bananas-smash.md, .changeset/thick-planes-clean.md, packages/ui/stepper/src/Stepper.tsx, packages/ui/stepper/src/utils.ts
=> feat(stepper): 支持配置字段别名(#2914)

.changeset/cuddly-ligers-deny.md, .changeset/many-moose-matter.md, packages/ui/transfer/src/Transfer.tsx, packages/ui/transfer/src/utils.ts
=> feat(transfer): 支持配置字段别名(#2909)

.changeset/angry-bugs-fix.md, .changeset/slimy-spoons-jog.md, packages/ui/list/src/List.tsx, packages/ui/list/src/utils.ts
=> feat(list): 支持配置字段别名(#2908)

.changeset/hot-ways-knock.md, .changeset/warm-zebras-sip.md, packages/ui/check-cascader/src/CheckCascader.tsx, packages/ui/check-cascader/stories/custom-render.stories.tsx, packages/ui/check-cascader/stories/index.stories.tsx
=> feat(check-cascader): 新增自定义触发器(#2896)

.changeset/itchy-items-end.md, .changeset/smooth-pears-behave.md, packages/ui/cascader/src/Cascader.tsx, packages/ui/cascader/stories/custom-render.stories.tsx, packages/ui/cascader/stories/index.stories.tsx
=> feat(cascader): 新增自定义触发器(#2888)

.changeset/forty-monkeys-hear.md, .changeset/kind-bikes-smile.md, packages/ui/date-picker/src/components/calendar.tsx, packages/ui/date-picker/src/types.ts
=> feat(date-picker): cellRender增加date参数

.changeset/eight-poets-reply.md, .changeset/sweet-garlics-shop.md, packages/ui/tabs/src/TabList.tsx
=> fix(tabs): 修复activeId为一个不存在的值或空值，下划线显示不对的问题(#2939)

.changeset/brown-poems-accept.md, .changeset/quick-seas-allow.md, packages/ui/dropdown/src/Dropdown.tsx, packages/ui/dropdown/src/use-dropdown.tsx
=> fix(dropdown): 修复overlay={{className: 'xx'}} 不生效问题

.changeset/curvy-falcons-confess.md, .changeset/old-penguins-grin.md, packages/ui/form/src/use-form-field.ts
=> fix(form): 修复validator回调中第一个参数带有多余的引号(#2931)

.changeset/quick-plums-cough.md, .changeset/short-timers-trade.md, packages/ui/pagination/src/DefaultPagination.tsx
=> fix(pagination): 修复 onJump 事件没有触发的问题(#2929)

.changeset/five-mails-beg.md, packages/ui/notification/src/styles/notification.scss
=> chore(notification): add overflow hidden for notification wrap style

.changeset/honest-tomatoes-work.md, .changeset/nine-kings-behave.md, packages/ui/tree/src/Tree.tsx, packages/ui/tree/src/TreeNode.tsx, packages/ui/tree/src/context.ts, packages/ui/tree/stories/icon-render.stories.tsx, packages/ui/tree/stories/index.stories.tsx
=> feat(tree): 新增 icon 支持自定义渲染函数(#2960)

.changeset/grumpy-clocks-attend.md, .changeset/moody-parents-scream.md, packages/ui/table/src/Table.tsx, packages/ui/table/src/hooks/use-check.ts, packages/ui/table/src/types.ts, packages/ui/table/stories/row-selection.stories.tsx
=> feat(table): 行选中增加单选

.changeset/eighty-kids-rest.md, .changeset/yellow-plums-boil.md, packages/ui/check-select/src/CheckSelect.tsx
=> feat(check-select): 支持回车键不默认选中功能(#2969)

.changeset/clean-donuts-attack.md, .changeset/hot-fans-beg.md, .changeset/metal-squids-unite.md, .changeset/silver-ads-jog.md, .changeset/slow-bottles-talk.md, .changeset/tall-walls-doubt.md, packages/ui/date-picker/CHANGELOG.md, packages/ui/date-picker/package.json, packages/ui/hiui/CHANGELOG.md, packages/ui/hiui/package.json
=> Revert "Release"

.changeset/clean-beans-sniff.md, .changeset/clever-donuts-smash.md, packages/ui/table/src/styles/table.scss
=> style(table): 优化 resizable 模式下列 hover 时样式 (#2996)

.changeset/pretty-trains-bake.md, packages/ui/tree/src/hooks/use-focus.ts
=> fix: 修复选项禁用时触发键盘事件报错

.changeset/green-points-sort.md, packages/ui/table/src/SettingDrawer.tsx
=> feat(table): SettingDrawer 增加 onReset api (#3021)

.changeset/brown-clouds-deny.md, packages/ui/pagination/src/DefaultPagination.tsx, packages/ui/pagination/src/PageJumper.tsx, packages/ui/pagination/src/PageOption.tsx, packages/ui/pagination/src/Pagination.tsx, packages/ui/pagination/src/ShrinkPagination.tsx, packages/ui/pagination/src/styles/pagination.scss, packages/ui/pagination/stories/index.stories.tsx, packages/ui/pagination/stories/size.stories.tsx
=> feat(pagination): add size api (#3047)

.changeset/proud-beers-guess.md, packages/ui/table/src/TableCell.tsx, packages/ui/table/src/TheadContent.tsx, packages/ui/table/src/styles/table.scss, packages/ui/table/src/use-table.ts, packages/ui/table/stories/resizable.stories.tsx
=> Revert "fix(table): 在 resizable 模式下,将拖拽线高度拉长至覆盖当前列所有单元格中 (#3049)"

.changeset/beige-months-poke.md, packages/ui/table/src/hooks/use-col-width.ts, packages/ui/table/src/styles/table.scss, packages/ui/table/src/use-table.ts, packages/ui/table/stories/data-sorter.stories.tsx, packages/ui/table/stories/scrollbar.stories.tsx, stories/Introduction.stories.mdx
closed #3046 
在 resizable 模式下，支持一种新的拖拽交互：拖拽改变当前列时，不改变其他列宽，表格的宽度自适应
=> feat(table): add tableWidthAdjustOnResize api (#3046)

.changeset/selfish-seas-impress.md, packages/ui/date-picker/src/DatePicker.tsx, packages/ui/date-picker/src/components/range-panel.tsx, packages/ui/date-picker/src/context.ts
=> perf(date-picker): 范围选择交互优化 (#3055)

.changeset/lazy-tools-admire.md, packages/ui/locale-context/src/locale/en-US.ts
=> fix(locale-context): 修改英文前往(#3062)

.changeset/rotten-buckets-look.md, packages/ui/date-picker/src/styles/date-picker.scss
=> perf(date-picker): 图标固定在右边 (#3077)

.changeset/purple-ligers-heal.md, packages/ui/drawer/src/Drawer.tsx
=> fix(drawer): 修复局部显示中设置 showMask={false} 后显示异常问题 (#3080)

.changeset/sour-impalas-eat.md, packages/ui/table/src/BaseTable.tsx
=> fix(table): 修复空状态下设置边框左边框不显示问题 (#3082)

.changeset/little-turkeys-juggle.md, packages/ui/table/src/use-table.ts
=> fix(table): 修复表头分组下设置列排序无效问题 (#3085)

.changeset/warm-taxis-grow.md, packages/ui/input/src/Input.tsx, packages/ui/input/src/use-input.ts
=> feat(input): add waitCompositionEnd api (#3090)

.changeset/real-zoos-serve.md, packages/ui/date-picker/src/components/footer.tsx, packages/ui/date-picker/src/components/panel.tsx, packages/ui/date-picker/src/components/range-panel.tsx, packages/ui/date-picker/src/types.ts, packages/ui/date-picker/stories/footer-render.stories.tsx
=> feat(date-picker): 完善 footerRender 功能 (3088)

.changeset/dirty-zebras-teach.md, packages/ui/tag-input/src/TagInputMock.tsx
=> perf(tag-input): 优化 wrap 模式下设置 displayRender 卡顿问题 (#3094)

.changeset/itchy-tigers-sleep.md, packages/ui/ellipsis-tooltip/src/EllipsisTooltip.tsx
=> feat(ellipsis-tooltip): 支持标记 Tooltip 可用状态 (#3097)

.changeset/gentle-flowers-sell.md, packages/ui/modal/src/Modal.tsx, packages/ui/modal/src/with-api.tsx, packages/ui/modal/stories/with-api.stories.tsx
=> feat(modal): 以 api 方式调用时支持异步关闭弹窗 (#3012)

.changeset/serious-islands-listen.md, packages/ui/highlighter/src/Highlighter.tsx, packages/ui/highlighter/stories/index.stories.tsx, packages/ui/highlighter/stories/rule.stories.tsx, packages/ui/highlighter/stories/style.stories.tsx
=> feat(highlighter): 支持设置高亮样式 (#3076)

.changeset/six-windows-call.md, .storybook/themes/hiui-theme.js, packages/ui/transfer/src/Transfer.tsx, packages/ui/transfer/src/TransferPanel.tsx, packages/ui/transfer/src/context.ts, packages/ui/transfer/stories/searchable.stories.tsx
=> feat(transfer): Add keyword and onSearch api (#3099)

.changeset/rare-parrots-serve.md, packages/ui/table/src/TableBody.tsx, packages/ui/table/src/TableRow.tsx
=> fix(table): 修复虚拟表格下自定义行和单元格样式无效问题 (#3100)

.changeset/selfish-suits-listen.md, packages/ui/time-picker/src/TimePicker.tsx
=> fix(time-picker): 修复点击叉号关闭弹窗时没有触发 onChange 事件问题 (#3106)

.changeset/curly-grapes-sort.md, packages/ui/progress/src/CircleProgress.tsx, packages/ui/progress/src/DashboardProgress.tsx, packages/ui/progress/src/Progress.tsx
=> fix(progress): 修复 color 设置无效问题 (#3111)

.changeset/curvy-rivers-promise.md, packages/ui/check-select/src/CheckSelect.tsx, packages/ui/check-select/stories/custom-render.stories.tsx
=> fix(check-select): 修复 customRender 回调中的 value 值无法显示初始值问题 (#3113)

.changeset/silly-paws-nail.md, packages/ui/date-picker/src/styles/date-picker.scss
=> fix(date-picker): 添加头部操作区域用户选择样式以改善交互体验 (#3117)

.changeset/neat-jeans-design.md, packages/ui/popover/src/use-popover.tsx
=> feat(popover): 添加自定义 popper.js 装饰器支持，增强 UsePopoverProps 接口 (#3123)

.changeset/shiny-fans-rest.md, packages/ui/check-select/src/CheckSelect.tsx, packages/ui/check-select/src/utils/index.ts
=> fix(check-select): 优化 customRender 回调参数的值 (#3124)

.changeset/neat-jeans-design.md, .changeset/wise-icons-attack.md, packages/ui/popover/src/use-popover.tsx, packages/ui/popper/src/index.ts, packages/ui/popper/src/use-popper.ts
=> chore(popper): 暴露 modifiers 参数 (#3127)

.changeset/thick-actors-give.md, packages/ui/date-picker/src/DatePicker.tsx, packages/ui/date-picker/src/types.ts
=> feat(date-picker): 添加可选的 visible 属性以控制日期选择器的显示状态 (#3131)

.changeset/gold-jeans-search.md, packages/ui/date-picker/src/DatePicker.tsx
=> fix(date-picker): 在日期选择器中添加 onClose 回调 (#3133)

.changeset/bright-seahorses-smoke.md, packages/ui/cascader/src/hooks/use-select.ts, packages/ui/cascader/src/use-cascader.ts
=> feat(cascader): useSelect 增加 value 参数以支持选中项的初始化状态 (#3135)

.changeset/dull-donuts-fold.md, .changeset/plenty-eggs-impress.md, packages/core/core/src/index.ts, packages/ui/cascader/stories/size.stories.tsx, packages/ui/check-cascader/stories/size.stories.tsx, packages/ui/check-select/src/CheckSelect.tsx, packages/ui/check-select/stories/size.stories.tsx, packages/ui/check-tree-select/stories/size.stories.tsx, packages/ui/input/src/Input.tsx, packages/ui/input/src/MockInput.tsx, packages/ui/input/src/styles/input.scss, packages/ui/input/src/styles/mock-input.scss, packages/ui/input/stories/index.stories.tsx, packages/ui/input/stories/size.stories.tsx, packages/ui/picker/src/styles/picker.scss, packages/ui/picker/stories/basic.stories.tsx, packages/ui/select/stories/size.stories.tsx, packages/ui/tag-input/src/TagInputMock.tsx, packages/ui/tag-input/src/styles/tag-input-mock.scss, packages/ui/tree-select/stories/size.stories.tsx
新版 Select、CheckSelect、TreeSelect、CheckTreeSelect、Cascader、CheckCascader、Input
=> Next 5.0/select

.changeset/modern-fishes-draw.md, packages/core/core-css/src/styles/themes/border.scss, packages/core/core-css/src/styles/tokens/border.scss, packages/ui/button/src/styles/base.scss, packages/ui/date-picker/src/styles/date-picker.scss, packages/ui/date-picker/src/types.ts, packages/ui/date-picker/stories/size.stories.tsx, packages/ui/input/src/styles/mock-input.scss, packages/ui/tag-input/src/styles/tag-input-mock.scss
=> feat(date-picker): 新版 DatePicker (5.0)

.changeset/bright-pumpkins-pretend.md, .changeset/slimy-humans-pretend.md, .changeset/tough-pigs-hug.md, .changeset/young-toes-enjoy.md, packages/ui/drawer/src/Drawer.tsx, packages/ui/drawer/src/styles/drawer.scss, packages/ui/drawer/stories/basic.stories.tsx, packages/ui/drawer/stories/extra.stories.tsx, packages/ui/drawer/stories/footer.stories.tsx, packages/ui/drawer/stories/mask.stories.tsx, packages/ui/drawer/stories/outside-click.stories.tsx, packages/ui/drawer/stories/placement.stories.tsx, packages/ui/modal/src/Modal.tsx, packages/ui/modal/src/styles/modal.scss, packages/ui/modal/stories/popup.stories.tsx, packages/ui/result/src/types.ts, packages/ui/space/src/types.ts, packages/ui/space/src/utils/index.ts, packages/ui/tag/src/styles/tag-group.scss, packages/ui/tag/stories/editor-render.stories.tsx, stories/Introduction.stories.mdx
1. 修改 Drawer 样式
2. 修改 Modal 样式
3. 修复 Tag 添加时抖动问题
4. 修改 Space 和 Result 组件 size 类型
=> Next 5.0/tag modal drawe

packages/ui/form/src/FormList.tsx, packages/ui/form/src/index.ts, packages/ui/number-input/src/styles/number-input.scss
详细清单：
- feat(form): 主入口新增FormLabel的组件导出
- feat(form): 更新FormListProps中children渲染函数的fields参数的参数类型
- feat(number-input): 容器元素新增默认的白色背景色
=> feat: 更新Form的组件导出清单/NumberInput新增默认的白色背景等

.changeset/rich-bugs-smell.md, .changeset/tall-drinks-impress.md, packages/ui/date-picker/src/DatePicker.tsx, packages/ui/date-picker/src/components/root.tsx, packages/ui/date-picker/src/styles/date-picker.scss, packages/ui/date-picker/src/types.ts, packages/ui/date-picker/stories/appearance.stories.tsx, packages/ui/date-picker/stories/basic.stories.tsx, packages/ui/input/src/MockInput.tsx, packages/ui/tag-input/src/TagInputMock.tsx
1. DatePicker appearance 参数增加 contained 类型
2. 优化 Input 和 TagInput label显示逻辑
=> feat(date-picker): appearance 参数增加 contained 类型

.changeset/many-pillows-tease.md, packages/ui/upload/src/DragUpload.tsx, packages/ui/upload/src/utils.ts
fix(upload): upload组件支持上传的文件异常(#3163)
=> fix(upload): Upload drag 模式下 accept 设置 * 号后无法上传文件(#3163)

.changeset/itchy-impalas-happen.md, packages/ui/dropdown/src/Dropdown.tsx, packages/ui/dropdown/src/styles/dropdown.scss, packages/ui/dropdown/stories/index.stories.tsx, packages/ui/popper/src/styles/popper.scss
=> style(dropdown): 下拉框带边框&圆角改为 6px&size 改为只有 md 尺寸 (5.0)

.changeset/flat-taxis-pump.md, .changeset/smart-jokes-smash.md, packages/ui/upload/src/AvatarUpload.tsx, packages/ui/upload/src/FileList.tsx, packages/ui/upload/src/NormalUpload.tsx, packages/ui/upload/src/PictureListUpload.tsx, packages/ui/upload/src/PictureUpload.tsx, packages/ui/upload/src/hooks/use-upload.ts, packages/ui/upload/src/styles/upload.scss, packages/ui/upload/src/types.ts, packages/ui/upload/src/utils.ts, packages/ui/upload/stories/action-render.stories.tsx, packages/ui/upload/stories/async-upload-action.stories.tsx, packages/ui/upload/stories/avatar.stories.tsx, packages/ui/upload/stories/basic.stories.tsx, packages/ui/upload/stories/controlled.stories.tsx, packages/ui/upload/stories/custom-upload.stories.tsx, packages/ui/upload/stories/draggable.stories.tsx, packages/ui/upload/stories/index.stories.tsx, packages/ui/upload/stories/photo.stories.tsx, packages/ui/upload/stories/picture-card.stories.tsx, packages/ui/upload/stories/single-import.stories.tsx, packages/ui/upload/stories/size.stories.tsx
1. 5.0 风格
2. 新增上传成功后显示成功 icon
3. 增加 size 参数
4. 上传按钮改为线性
5. 照片墙上传按钮支持配置文案
=> style(upload): 新版 Upload (5.0)

.changeset/neat-walls-breathe.md, .changeset/tidy-onions-pay.md, packages/ui/tag/src/Tag.tsx, packages/ui/tag/src/styles/tag.scss, packages/ui/tag/stories/index.stories.tsx, packages/ui/tag/stories/trigger-edit.stories.tsx
closed https://github.com/XiaoMi/hiui/issues/3185
=> feat(tag): Tag 组件 render 方法增加 triggerEdit 参数用于触发编辑状态(#3185)

.changeset/lovely-icons-move.md, packages/ui/check-select/src/CheckSelect.tsx, packages/ui/select/src/Select.tsx, packages/ui/select/src/SelectOption.tsx, packages/ui/select/src/SelectOptionGroup.tsx, packages/ui/select/src/styles/select.scss
=> fix(select): 修复多级分组下分组标题左间距不对问题 (#3207)

.changeset/silly-comics-bow.md, packages/ui/table/src/hooks/use-col-width.ts, packages/ui/table/src/types.ts, packages/ui/table/src/utils/index.ts, packages/ui/table/stories/resizable.stories.tsx
=> feat(table): TableColumnItem 类型增加 minWidth 参数 (#3216)

.changeset/popular-boxes-love.md, packages/ui/cascader/src/use-cascader.ts, packages/ui/check-cascader/src/CheckCascader.tsx
=> feat(cascader): onChange 回调中增加选中项对象参数返回 (#3230)

.changeset/thirty-news-melt.md, packages/ui/date-picker/src/DatePicker.tsx, packages/ui/date-picker/src/components/calendar.tsx, packages/ui/date-picker/src/components/panel.tsx, packages/ui/date-picker/src/components/range-panel.tsx, packages/ui/date-picker/src/context.ts, packages/ui/date-picker/src/hooks/useCalenderData.tsx, packages/ui/date-picker/src/hooks/useData.ts, packages/ui/date-picker/src/types.ts, packages/ui/date-picker/src/utils/index.tsx, packages/ui/date-picker/stories/index.stories.tsx, packages/ui/date-picker/stories/utc-offset.stories.tsx
=> feat(date-picker): add utcOffset api (#3232)

.changeset/sharp-avocados-beam.md, packages/ui/form/src/use-form-field.ts, packages/ui/form/stories/validate.stories.tsx
=> fix(form): 优化 valueType 为 number 情况下的校验逻辑 (#3274)

.changeset/late-pots-explode.md, packages/ui/form/src/use-form-field.ts
=> fix(form): 处理规则消息为空的情况，将其设置为 undefined (#3276)

.changeset/sour-moons-eat.md, packages/ui/number-input/src/NumberInput.tsx
=> fix(number-input): 为加减按钮添加 type 属性，确保按钮行为符合标准 (#3278)

.changeset/mighty-ears-brake.md, packages/ui/table/src/BaseTable.tsx, packages/ui/table/src/TbodyContent.tsx, packages/ui/table/src/context.ts, packages/ui/table/src/styles/table.scss
=> feat(table): 增加 fixedToRow api，支持设置行固定到顶部或底部 (#3304)

.changeset/nice-turkeys-pump.md, packages/ui/time-picker/src/TimePicker.tsx
=> fix(time-picker): 优化默认值处理逻辑，确保在没有传值时使用默认值 (3302)

.changeset/few-plants-refuse.md, packages/ui/check-cascader/src/CheckCascader.tsx
=> fix(check-cascader): 修复 onChange 第三个参数返回的值和类型不匹配问题 (#3325)

.changeset/cool-radios-juggle.md, packages/ui/table/src/hooks/use-col-width.ts
=> fix(table): 优化列宽设置逻辑，确保在列变化时准确计算并更新列宽 (#3327)

.changeset/lemon-meals-jog.md, packages/hooks/use-search-mode/src/index.ts
=> fix(use-search-mode): 优化初次搜索逻辑 (#3335)
